"""Shape-aware reader merge (wowtalents.merge) and scripts/merge_readers.py.

Every case here is a real record from the 2026-09-13 data audit, so the tests say what the
merge is for as well as what it does.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
sys.path.insert(0, str(ROOT / "src"))

from wowtalents import merge as M  # noqa: E402

_spec = importlib.util.spec_from_file_location("merge_readers", ROOT / "scripts" / "merge_readers.py")
MR = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
_spec.loader.exec_module(MR)


# --------------------------------------------------------------------------- classify

@pytest.mark.parametrize("a,b,kind", [
    ("Increases", "increases", M.CASE),
    ("fire", "Fire", M.CASE),
    ("50.", "50%.", M.PERCENT),
    ("{0}.", "{0}%.", M.PERCENT),
    ("Bolt.", "Bolt,", M.PUNCT),
    ("sec.", "sec,", M.PUNCT),
    ("Bolt.", "bolt,", M.CASE),            # case and punctuation at once; either label, authority wins
    ("30.", "30%,", M.PERCENT),
    ("Hurts", "Hurls", M.WORD),
    ("Scorpion", "Scorpid", M.WORD),
    ("same", "same", ""),
])
def test_classify_pair(a, b, kind):
    assert M.classify_pair(a, b) == kind


# --------------------------------------------------------------------------- merge

def test_second_reader_wins_on_case():
    """audit 3.1: 27 records read `Increases`/`Instant` mid-sentence; the glyph is x-height."""
    res = M.merge_readings("... and Increases all threat generated by 30%.",
                           "... and increases all threat generated by 30%.")
    assert res.text.endswith("and increases all threat generated by 30%.")
    assert res.counts() == {M.CASE: 1}


def test_second_reader_wins_on_comma_read_as_period():
    """audit 3.2: druid/ferocity reads the same glyph as ',' after Maul and '.' after Mangle."""
    res = M.merge_readings("Reduces the cost of your Maul, Mangle. Swipe. Claw, and Rake abilities by 10 Rage.",
                           "Reduces the cost of your Maul, Mangle, Swipe, Claw, and Rake abilities by 10 Rage.")
    assert res.text == "Reduces the cost of your Maul, Mangle, Swipe, Claw, and Rake abilities by 10 Rage."
    assert res.counts() == {M.PUNCT: 2}


def test_second_reader_wins_on_a_dropped_percent():
    """audit 3.3: the most damaging shape - a percentage silently becomes a flat number
    that the rank scaler then multiplies (mage/shatter produced 150 % crit)."""
    res = M.merge_readings("Increases the critical strike chance against frozen targets by 50.",
                           "Increases the critical strike chance against frozen targets by 50%.")
    assert res.text.endswith("by 50%.")
    assert res.counts() == {M.PERCENT: 1}


def test_wording_goes_to_the_majority_not_to_the_second_reader():
    """audit 3.4: mage/pyroblast - the 2x Qwen pass and codex both read 'Hurls'."""
    res = M.merge_readings("Hurts an immense fiery boulder that inflicts damage.",
                           "Hurls an immense fiery boulder that inflicts damage.",
                           ["Hurls an immense fiery boulder that inflicts damage."])
    assert res.text.startswith("Hurls")
    assert res.counts() == {M.WORD: 1}


def test_wording_stays_with_the_primary_when_the_second_reader_is_alone():
    """audit 2: in 21 of the 77 queue records the second reader was the one that was wrong
    (druid/furor 'regain', not codex's 'retain')."""
    res = M.merge_readings("you regain 10 rage", "you retain 10 rage", ["you regain 10 rage"])
    assert res.text == "you regain 10 rage"
    assert res.counts() == {}


def test_an_unbacked_word_disagreement_is_reported_as_disputed():
    res = M.merge_readings("you regain 10 rage", "you retain 10 rage")
    assert res.text == "you regain 10 rage"          # tie: the primary reader keeps it
    assert [h.primary for h in res.disputed_words] == ["regain"]


def test_inserted_and_deleted_runs_are_voted_on_as_wording():
    """priest/devouring-contagion: a spurious 'it' the primary reader invented."""
    res = M.merge_readings("while Devouring Plague it is active", "while Devouring Plague is active",
                           ["while Devouring Plague is active"])
    assert res.text == "while Devouring Plague is active"
    assert res.counts() == {M.WORD: 1}


def test_case_punct_and_percent_in_one_description():
    res = M.merge_readings("Deals damage to Lightning Bolt. Chain Lightning and Increases it by 5.",
                           "Deals damage to Lightning Bolt, Chain Lightning and increases it by 5%.")
    assert res.text == "Deals damage to Lightning Bolt, Chain Lightning and increases it by 5%."
    assert res.counts() == {M.PUNCT: 1, M.CASE: 1, M.PERCENT: 1}


def test_identical_readings_change_nothing():
    text = "Increases the damage done by your Entangling Roots spell by 5%."
    res = M.merge_readings(text, text)
    assert res.text == text and not res.changed and res.counts() == {}


def test_an_empty_or_missing_second_reading_leaves_the_primary_alone():
    assert M.merge_readings("primary text", "").text == "primary text"
    assert M.merge_readings("", "secondary text").text == "secondary text"


def test_merge_never_invents_words_outside_the_two_readings():
    a, b = "alpha beta gamma delta", "alpha BETA gamma epsilon zeta"
    res = M.merge_readings(a, b)
    for word in res.text.split():
        assert word in a.split() or word in b.split()


# --------------------------------------------------------------------------- capital I

def test_capital_i_normaliser_lowercases_mid_sentence_words():
    out, fixed = M.normalise_capital_i("the armor from items is Increased by 10% while Instant casts remain.")
    assert out == "the armor from items is increased by 10% while instant casts remain."
    assert fixed == ["Increased", "Instant"]


def test_capital_i_normaliser_keeps_game_terms_and_sentence_openers():
    """audit 3.1: 40 of the 67 mid-sentence I-words are proper nouns; the reader is not
    simply capital-happy and those must not be touched."""
    text = "Increases your Intellect and your Imp's Immolate damage. Increases it further."
    out, fixed = M.normalise_capital_i(text)
    assert out == text and fixed == []


@pytest.mark.parametrize("text", [
    "Instant cast.",                               # line start
    "Passive: Instant cast is granted.",           # after a colon
    "It ends. Increases damage.",                  # after a full stop
])
def test_capital_i_normaliser_never_touches_a_sentence_opener(text):
    assert M.normalise_capital_i(text)[0] == text


# --------------------------------------------------------------------------- spell names

@pytest.fixture(scope="module")
def prior_doc() -> dict:
    return json.loads((REPO / "data" / "prior" / "classic-era" / "talents.json").read_text(encoding="utf-8"))


@pytest.mark.parametrize("cls,text,expected", [
    ("warlock", "an additional 25% damage if the target is afflicted by Immolates.",
     "an additional 25% damage if the target is afflicted by Immolate."),
    ("hunter", "Increases the damage of your Scorpion Sting ability by 6%.",
     "Increases the damage of your Scorpid Sting ability by 6%."),
    ("druid", "Reduces the mana cost of your Healing Touch and Tranquillity spells by 2%.",
     "Reduces the mana cost of your Healing Touch and Tranquility spells by 2%."),
])
def test_spell_name_repair_fixes_the_audits_cases(prior_doc, cls, text, expected):
    vocab = MR.class_vocabulary(prior_doc, cls)
    assert M.repair_spell_names(text, vocab)[0] == expected


@pytest.mark.parametrize("cls,text", [
    ("druid", "Your Mangle ability deals more damage."),          # a global dictionary reaches 'Mage'
    ("druid", "Bleeding effects last longer."),                   # ... and 'Blessing'
    ("mage", "Your Freeze effects are improved."),                # ... and 'Frenzy'
    ("rogue", "Increases the damage your Poisons deal."),         # a real plural, not a misread name
    ("warlock", "Reduces the Soul Shards consumed."),
    ("hunter", "Your new Forever ability Sunder Volley hits harder."),
])
def test_spell_name_repair_leaves_legitimate_text_alone(prior_doc, cls, text):
    vocab = MR.class_vocabulary(prior_doc, cls)
    assert M.repair_spell_names(text, vocab) == (text, [])


def test_spell_name_repair_takes_the_nearest_candidate():
    assert M.repair_spell_names("your Frostbalt spell", {"Frost Bolt", "Frostbolt"})[1] == [("Frostbalt", "Frostbolt")]


def test_spell_name_repair_refuses_an_ambiguous_snap():
    """Two prior terms equally close: repairing would be a coin toss, so nothing is repaired."""
    assert M.repair_spell_names("your Blaster spell", {"Blastar", "Blastor"}) == ("your Blaster spell", [])


def test_spell_name_repair_needs_a_vocabulary():
    assert M.repair_spell_names("your Immolates spell", set()) == ("your Immolates spell", [])


def test_class_vocabulary_is_scoped_to_one_class(prior_doc):
    warlock = MR.class_vocabulary(prior_doc, "warlock")
    druid = MR.class_vocabulary(prior_doc, "druid")
    assert "Immolate" in warlock and "Immolate" not in druid
    assert MR.class_vocabulary(prior_doc, "no-such-class") == set()


# --------------------------------------------------------------------------- record level

def _rec(desc: str, readings: list[tuple[str, str]], conf: float = 0.7, cls: str = "shaman") -> dict:
    return {"id": f"{cls}/t/r0c0", "class": cls, "name": "Concussion", "rank": {"current": 0, "max": 5},
            "description_rank1": desc, "ranks_anticipated": {"description": "stale", "ranksSource": "observed"},
            "source": {"confidence": conf, "reader": "qwen",
                       "note": "second reader (codex) differs in description",
                       "readings": [{"reader": r, "name": "Concussion", "description": d, "maxRank": 5,
                                     "confidence": 1.0} for r, d in readings]}}


def test_apply_merge_rewrites_the_record_and_clears_the_queue_flag():
    rec = _rec("Increases the damage of Lightning Bolt. Chain Lightning by 5.",
               [("qwen/3x", "Increases the damage of Lightning Bolt. Chain Lightning by 5."),
                ("qwen/2x", "Increases the damage of Lightning Bolt. Chain Lightning by 5."),
                ("codex-cli", "Increases the damage of Lightning Bolt, Chain Lightning by 5%.")])
    rep = MR.apply_merge(rec, set(), at="2026-09-13T00:00:00Z")
    assert rec["description_rank1"] == "Increases the damage of Lightning Bolt, Chain Lightning by 5%."
    assert rep["shapes"] == {M.PUNCT: 1, M.PERCENT: 1}
    assert rec["source"]["confidence"] == 1.0        # the disagreement is settled: out of the queue
    assert "note" not in rec["source"]               # the stale "second reader differs" clause is gone
    assert "ranks_anticipated" not in rec            # stage 6/8 re-derives the template and the ranks
    pre = [r for r in rec["source"]["readings"] if r["reader"] == "pre-merge"]
    assert len(pre) == 1 and pre[0]["description"].endswith("by 5.")   # provenance kept


def test_apply_merge_keeps_a_disputed_record_in_the_queue():
    rec = _rec("you regain 10 rage", [("qwen/3x", "you regain 10 rage"), ("codex-cli", "you retain 10 rage")])
    rep = MR.apply_merge(rec, set(), at="t")
    assert rec["description_rank1"] == "you regain 10 rage"
    assert rec["source"]["confidence"] == 0.7
    assert "readers still differ on 'regain' vs 'retain'" in rec["source"]["note"]
    assert rep["changed"] is False
    assert "ranks_anticipated" in rec                # nothing changed, so nothing to recompute


def test_apply_merge_is_idempotent():
    rec = _rec("Lightning Bolt. Chain Lightning",
               [("qwen/3x", "Lightning Bolt. Chain Lightning"), ("codex-cli", "Lightning Bolt, Chain Lightning")])
    MR.apply_merge(rec, set(), at="t")
    first = json.dumps(rec, sort_keys=True)
    MR.apply_merge(rec, set(), at="t")
    assert json.dumps(rec, sort_keys=True) == first


def test_apply_merge_leaves_a_clean_records_text_alone_and_clears_its_stale_note():
    text = "Reduces the mana cost of your Shock spells by 2%."
    rec = _rec(text, [("qwen/3x", text), ("codex-cli", text)], conf=1.0)
    assert MR.apply_merge(rec, set(), at="t") is None
    assert rec["description_rank1"] == text and rec["name"] == "Concussion"
    assert rec["source"]["confidence"] == 1.0
    assert "note" not in rec["source"]          # the superseded "second reader differs" clause is gone
    assert "ranks_anticipated" in rec


def test_spell_name_repair_only_runs_inside_the_review_queue(prior_doc):
    """Census over all 469 records: the dictionary is right 6/6 inside the queue and wrong
    8/8 outside it, and every text error the audit found sits inside the queue."""
    vocab = MR.class_vocabulary(prior_doc, "warlock")
    text = "damage if the target is afflicted by Immolates."
    queued = _rec(text, [("qwen/3x", text), ("codex-cli", text)], conf=0.7, cls="warlock")
    MR.apply_merge(queued, vocab, at="t")
    assert queued["description_rank1"].endswith("Immolate.")
    trusted = _rec(text, [("qwen/3x", text), ("codex-cli", text)], conf=1.0, cls="warlock")
    assert MR.apply_merge(trusted, vocab, at="t") is None
    assert trusted["description_rank1"].endswith("Immolates.")


def test_note_handling_keeps_unrelated_clauses():
    assert MR.strip_merge_clauses("points already spent; second reader (codex) differs in description") == \
        "points already spent"
    assert MR.strip_merge_clauses(None) == ""
    src = {"note": "points already spent; readers still differ on 'x' vs 'y'"}
    MR.set_note(src, "readers still differ on 'a' vs 'b'")
    assert src["note"] == "points already spent; readers still differ on 'a' vs 'b'"


def test_set_note_is_idempotent_and_drops_a_settled_clause():
    src = {"note": "points already spent"}
    for _ in range(3):
        MR.set_note(src, "readers still differ on 'a' vs 'b'", "crop is 181 px wide and missing a tooltip border")
    assert src["note"] == ("points already spent; readers still differ on 'a' vs 'b'; "
                           "crop is 181 px wide and missing a tooltip border")
    # an older run's wording of the same clauses is stripped too, not stacked on top
    stale = {"note": "points already spent; footer (not adjudicated by the merge); "
                     "it is probably cut off and the reading cannot be verified; re-crop the cell"}
    MR.set_note(stale)
    assert stale["note"] == "points already spent"
    MR.set_note(src)                       # nothing open any more
    assert src["note"] == "points already spent"
    MR.set_note({"note": "readers still differ on 'a' vs 'b'"})
    src2 = {"note": "readers still differ on 'a' vs 'b'"}
    MR.set_note(src2)
    assert "note" not in src2              # an empty note is removed, not left as ""


def test_split_readings_finds_the_authority_anywhere_in_the_list():
    rec = _rec("x", [("qwen/3x", "a"), ("codex-cli", "b"), ("qwen/2x", "c")])
    primary, auth, others = MR.split_readings(rec)
    assert primary["reader"] == "qwen/3x" and auth["reader"] == "codex-cli"
    assert [o["reader"] for o in others] == ["qwen/2x"]


def test_queue_size_counts_below_the_validator_threshold():
    recs = [{"source": {"confidence": c}} for c in (1.0, 0.8, 0.79, 0.7, 0.3)]
    assert MR.queue_size(recs) == 3


def test_a_superseded_reading_never_votes_again():
    """The pre-merge text is kept as provenance; letting it vote would make a second run
    drift back towards the reading the first run rejected."""
    rec = _rec("Hurts an immense boulder",
               [("qwen/3x", "Hurts an immense boulder"), ("qwen/2x", "Hurls an immense boulder"),
                ("codex-cli", "Hurls an immense boulder")])
    MR.apply_merge(rec, set(), at="t")
    assert rec["description_rank1"] == "Hurls an immense boulder"
    labels = [r["reader"] for r in rec["source"]["readings"]]
    assert MR.PRE_MERGE_LABEL in labels
    primary, auth, others = MR.split_readings(rec)
    assert MR.PRE_MERGE_LABEL not in [r["reader"] for r in [primary, auth, *others] if r]
    MR.apply_merge(rec, set(), at="t")
    assert rec["description_rank1"] == "Hurls an immense boulder"


def test_a_name_disagreement_keeps_the_record_in_the_queue():
    """druid/feral-combat: Qwen read the Bear-form rage cost `5 Rage` as the talent name,
    codex read `Feral Charge`. Merging the descriptions must not clear that flag."""
    rec = _rec("Charge an enemy, immobilizing them.",
               [("qwen/3x", "Charge an enemy, immobilizing them."),
                ("codex-cli", "Charge an enemy, immobilizing them.")], conf=0.3, cls="druid")
    rec["name"] = "5 Rage"
    rec["source"]["readings"][1]["name"] = "Feral Charge"
    MR.apply_merge(rec, set(), at="t")
    assert rec["name"] == "5 Rage"                       # never silently replaced
    assert rec["source"]["confidence"] == 0.7            # still in the review queue
    assert "name '5 Rage' vs 'Feral Charge'" in rec["source"]["note"]


def test_a_case_only_name_difference_goes_to_the_authority():
    rec = _rec("x", [("qwen/3x", "x"), ("codex-cli", "x")], conf=0.7)
    rec["name"] = "holy fire"
    rec["source"]["readings"][1]["name"] = "Holy Fire"
    MR.apply_merge(rec, set(), at="t")
    assert rec["name"] == "Holy Fire" and rec["source"]["confidence"] == 1.0


# --------------------------------------------------------------------------- unadjudicated doubts

def test_a_doubt_the_merge_cannot_settle_keeps_the_record_flagged():
    """warlock/bane-of-havoc was at 0.7 because the two Qwen passes differed in `extra_lines`.
    All four descriptions agree, but clearing the flag would claim a resolution nobody reached."""
    text = "Afflicts the target for 5 min."
    rec = _rec(text, [("qwen/3x", text), ("qwen/2x", text), ("codex-cli", text)], conf=0.7)
    rec["source"]["note"] = None
    rec["source"]["agreement"] = {"confidence": 0.7, "differs_in": ["extra_lines"]}
    MR.apply_merge(rec, set(), at="t")
    assert rec["source"]["confidence"] == 0.7
    assert "extra_lines" in rec["source"]["note"]


def test_a_settled_description_only_doubt_leaves_the_queue():
    """warlock/agonizing-flames: the 2x pass dropped a '%'; three of four readings carry it."""
    good = "and the damage done by all your Destruction spells by 3%."
    rec = _rec(good, [("qwen/3x", good), ("qwen/2x", "and the damage done by all your Destruction spells by 3."),
                      ("codex-cli", good)], conf=0.7)
    rec["source"]["note"] = None
    rec["source"]["agreement"] = {"confidence": 0.7, "differs_in": ["description"]}
    MR.apply_merge(rec, set(), at="t")
    assert rec["source"]["confidence"] == 1.0 and "note" not in rec["source"]


def test_a_merged_record_with_a_leftover_doubt_stays_in_the_queue():
    rec = _rec("Lightning Bolt. Chain Lightning",
               [("qwen/3x", "Lightning Bolt. Chain Lightning"), ("codex-cli", "Lightning Bolt, Chain Lightning")],
               conf=0.7)
    rec["source"]["note"] = "second reader (codex) differs in rank_max, description"
    MR.apply_merge(rec, set(), at="t")
    assert rec["description_rank1"] == "Lightning Bolt, Chain Lightning"   # the punctuation is still fixed
    assert rec["source"]["confidence"] == 0.7
    assert "readers differ in rank_max, which the reader merge does not adjudicate" in rec["source"]["note"]


@pytest.mark.parametrize("src,expected", [
    ({"agreement": {"confidence": 0.7, "differs_in": ["description"]}}, []),
    ({"agreement": {"confidence": 0.7, "differs_in": ["description", "extra_lines"]}}, ["extra_lines"]),
    ({"agreement": {"confidence": 1.0, "differs_in": ["extra_lines"]}}, []),
    ({"note": "second reader (codex) differs in name, rank_max; something else"}, ["rank_max"]),
    ({}, []),
])
def test_unadjudicated_doubts(src, expected):
    assert MR.unadjudicated_doubts({"source": src}) == expected


# --------------------------------------------------------------------------- crop geometry

def test_suspect_crops_needs_both_a_missing_border_and_a_narrow_box():
    """Census over all 469 crops: a missing border alone flags 6 (5 of them just sit on a dark
    background), a narrow box alone flags 10 (9 are genuinely short tooltips). Together: 1."""
    geometry = {
        "cut": (181, 0.16),          # piercing-ice: narrow AND no right border
        "dark-background": (219, 0.16),
        "short-tooltip": (175, 0.72),
        **{f"normal-{i}": (221, 0.65) for i in range(6)},
    }
    assert MR.suspect_crops(geometry) == {"cut"}


def test_suspect_crops_needs_a_population_to_compare_against():
    assert MR.suspect_crops({"a": (181, 0.16), "b": (221, 0.65)}) == set()


def test_crop_geometry_reads_a_real_crop(tmp_path):
    import cv2
    import numpy as np
    img = np.zeros((60, 100, 3), np.uint8)
    img[:] = 10
    img[:3, :] = img[-3:, :] = img[:, :3] = img[:, -3:] = 200      # a complete border
    p = tmp_path / "whole.png"
    cv2.imwrite(str(p), img)
    w, ratio = MR.crop_geometry(p)
    assert w == 100 and ratio > 0.9
    img[:, -3:] = 10                                               # right border cut away
    p2 = tmp_path / "cut.png"
    cv2.imwrite(str(p2), img)
    assert MR.crop_geometry(p2)[1] < 0.2
    assert MR.crop_geometry(tmp_path / "missing.png") is None


def test_a_settled_record_leaves_the_queue_even_after_a_stale_run_flagged_it():
    """Confidence and note are recomputed from the evidence, never nudged, so a warning a
    previous run wrote (say, a crop rule that has since been tightened) does not linger."""
    text = "Reduces the mana cost of your Shock spells by 2%."
    rec = _rec(text, [("qwen/3x", text), ("codex-cli", text)], conf=0.7)
    rec["source"]["note"] = "points already spent; crop is 181 px wide and missing a tooltip border"
    MR.apply_merge(rec, set(), at="t")
    assert rec["source"]["confidence"] == 1.0
    assert rec["source"]["note"] == "points already spent"


def test_settle_puts_a_cut_off_crop_back_in_the_queue():
    text = "Increases the damage done by yo"
    rec = _rec(text, [("qwen/3x", text), ("codex-cli", text)], conf=1.0)
    MR.apply_merge(rec, set(), at="t")
    assert rec["source"]["confidence"] == 1.0
    MR.settle(rec, "crop is 181 px wide and missing a tooltip border, so the tooltip is cut off")
    assert rec["source"]["confidence"] == 0.7
    assert "181 px wide" in rec["source"]["note"]
    MR.settle(rec)                                   # re-cropped: the warning goes away again
    assert rec["source"]["confidence"] == 1.0 and "note" not in rec["source"]


def test_a_footer_only_difference_is_not_a_doubt():
    """Stage 5 lists `footer` in differs_in while keeping full confidence: the green
    "Click to learn" line is not talent data and must not fill the review queue."""
    rec = {"source": {"agreement": {"confidence": 1.0, "differs_in": ["footer"]}}}
    assert MR.unadjudicated_doubts(rec) == []
    rec2 = {"source": {"agreement": {"confidence": 0.7, "differs_in": ["footer", "extra_lines"]}}}
    assert MR.unadjudicated_doubts(rec2) == ["extra_lines"]
