/**
 * Everything `#/races` and `#/races/<race>` decide, as pure functions.
 *
 * The page model lives here for the same reason `changesModel.ts` does: the
 * matrix, the variant split and the Classic chips are rules, not markup, and
 * they are worth testing without a DOM. `RacesPage.tsx` supplies the data -
 * `races-index.json` for the overview, one race file for a race page - and
 * never computes anything itself.
 *
 * The rules this file enforces come from `docs/handover/2026-09-13-races-data.md`
 * section 5:
 *
 *   1. `observed: false` or an empty class list is **unknown**, never "no
 *      classes". No race is in that state today; the branch stays.
 *   2. Every trait is unreviewed, so the page carries the trust statement the
 *      talent tooltip carries - once, at the top, because all 37 readings agree
 *      and a per-card repeat would be 37 copies of one sentence. A trait that
 *      does fall below the review threshold gets the tooltip's own amber line.
 *   4. `classic.classicText` is a paraphrase written from memory. Every render
 *      of it is marked `unverified`.
 *   5. Traits are shown in `order`, the order of the box, never by name.
 *   7. A race with variants shows one variant at a time: its traits, its class
 *      list, its lore - not the union.
 */
import type { Faction, RaceData, RaceTrait, RaceVariant } from '../data/schema.races'
import { racesHash } from '../url/route'
import { internalId, needsReview, readingLine, streamStamp, trustLine, withPeriod } from './trust'

// --- the index (generated by scripts/gen-data-index.mjs) -------------------

export interface IndexVariant {
  id: string
  name: string
  faction: 'alliance' | 'horde'
  classes: string[]
  newCombos?: string[]
}

export interface IndexRace {
  id: string
  raceName: string
  faction: Faction
  classes: string[]
  observed: boolean
  complete: boolean
  traits: number
  counts: { new: number; changed: number; same: number; unknown: number }
  newCombos?: string[]
  variants?: IndexVariant[]
  reportedElsewhere?: string[]
  agreement?: string
  disagreement?: string
}

export interface RacesIndex {
  prior: string
  priorVerified: boolean
  classes: string[]
  races: IndexRace[]
  notes: string[]
}

// --- the matrix ------------------------------------------------------------

export interface MatrixRow {
  /** Unique per row: the race id, or `<race>:<variant>` for a variant row. */
  key: string
  raceId: string
  variantId?: string
  /** The variant's own name for a variant row ("Windshaper Skyborne"). */
  name: string
  faction: Faction
  classes: string[]
  /**
   * Classes this race could not be in Classic Era. `undefined` when the Classic
   * prior says nothing about the race, which is not the same as "none": the
   * table then marks no cell rather than inventing a claim.
   */
  newCombos?: string[]
  observed: boolean
  traits: number
  newTraits: number
  href: string
  /** The cross-check against third-party reports, when one was recorded. */
  note?: string
}

const FACTION_ORDER: Record<Faction, number> = { alliance: 0, horde: 1, neutral: 2 }

/**
 * One row per playable identity, which is not one row per race file: the two
 * Skyborne variants have different class bars (High Order has Mage, Windshaper
 * has Shaman), so collapsing them into one row would claim a Skyborne Mage can
 * join the Horde. They are separate rows, each on its own faction side.
 *
 * Rows are grouped Alliance, then Horde, then a race that is genuinely neutral,
 * and alphabetically inside a group - the arrangement of the character-creation
 * screen the data was read from.
 */
export function matrixRows(index: RacesIndex): MatrixRow[] {
  const rows: MatrixRow[] = []
  for (const race of index.races) {
    const note = race.disagreement ?? race.agreement
    const base = {
      raceId: race.id,
      traits: race.traits,
      newTraits: race.counts.new,
      observed: race.observed,
      ...(note ? { note } : {}),
    }
    if (race.variants && race.variants.length > 0) {
      for (const variant of race.variants) {
        rows.push({
          ...base,
          key: `${race.id}:${variant.id}`,
          variantId: variant.id,
          name: variant.name,
          faction: variant.faction,
          classes: variant.classes,
          ...(variant.newCombos ? { newCombos: variant.newCombos } : {}),
          href: racesHash(race.id, variant.id),
        })
      }
      continue
    }
    rows.push({
      ...base,
      key: race.id,
      name: race.raceName,
      faction: race.faction,
      classes: race.classes,
      ...(race.newCombos ? { newCombos: race.newCombos } : {}),
      href: racesHash(race.id),
    })
  }
  return rows.sort((a, b) => FACTION_ORDER[a.faction] - FACTION_ORDER[b.faction] || a.name.localeCompare(b.name))
}

export type CellState = 'new' | 'playable' | 'no' | 'unknown'

/**
 * What one cell of the matrix says. `unknown` is the branch rule 1 asks for: a
 * race whose class bar was never read has an empty list, and an empty list is
 * not a statement that the race can be nothing.
 */
export function cellState(row: MatrixRow, classId: string): CellState {
  if (!row.observed || row.classes.length === 0) return 'unknown'
  if (!row.classes.includes(classId)) return 'no'
  return row.newCombos?.includes(classId) ? 'new' : 'playable'
}

/** What a screen reader hears in a cell, and what the title attribute says. */
export function cellLabel(row: MatrixRow, className: string, state: CellState): string {
  switch (state) {
    case 'new':
      return `${row.name} ${className} - new in Forever`
    case 'playable':
      return `${row.name} ${className}`
    case 'unknown':
      return `${row.name}: the class list was never read`
    default:
      return `${row.name} cannot be a ${className}`
  }
}

/** How many combinations across the whole table are new against Classic. */
export function newComboCount(rows: MatrixRow[]): number {
  return rows.reduce((n, row) => n + (row.newCombos?.length ?? 0), 0)
}

// --- one race --------------------------------------------------------------

/**
 * Which variant a race page shows. Alliance first by default, as the data
 * handover asks; an unknown or absent id falls back to it rather than showing
 * an empty page.
 */
export function activeVariant(race: RaceData, requested: string | undefined): RaceVariant | undefined {
  const variants = race.variants
  if (!variants || variants.length === 0) return undefined
  return (
    variants.find((v) => v.id === requested) ?? variants.find((v) => v.faction === 'alliance') ?? variants[0]
  )
}

/**
 * The traits of one variant, in box order. A race without variants shows all of
 * them; a trait of a race *with* variants that names none is a data error the
 * validator catches, and is shown rather than silently dropped.
 */
export function variantTraits(race: RaceData, variant: RaceVariant | undefined): RaceTrait[] {
  const traits = race.traits.filter((t) => !variant || !t.variants || t.variants.includes(variant.id))
  return [...traits].sort((a, b) => a.order - b.order)
}

/** The class list to show: the variant's own, never the union across variants. */
export function variantClasses(race: RaceData, variant: RaceVariant | undefined): string[] {
  return variant ? variant.classes : race.classes
}

/** The lore paragraph to show, and whether it ran past the edge of the box. */
export function variantLore(
  race: RaceData,
  variant: RaceVariant | undefined,
): { text: string; complete: boolean } | undefined {
  const text = variant ? variant.lore : race.lore
  if (!text) return undefined
  const complete = (variant ? variant.loreComplete : race.loreComplete) ?? false
  return { text, complete }
}

// --- trust, the tooltip's rules applied to a page -------------------------

/**
 * The page's source statement, the one place the provenance is spelled out.
 * The talent tooltip puts at most one amber line on each card; here every card
 * would carry the same sentence, because all 37 readings agreed and none is
 * reviewed, so the statement is made once at the top and each card keeps only
 * its timestamp behind Details.
 */
export function raceTrustLines(traits: RaceTrait[]): string[] {
  const total = traits.length
  if (total === 0) return []
  const reviewed = traits.filter((t) => t.source.reviewed).length
  const shaky = traits.filter((t) => needsReview(t)).length
  const lines: string[] = []
  const noun = total === 1 ? 'trait' : 'traits'
  if (reviewed === 0) {
    lines.push(`Read from BlizzCon 2026 footage; not yet reviewed.`)
  } else if (reviewed === total) {
    lines.push(`Read from BlizzCon 2026 footage and reviewed.`)
  } else {
    lines.push(`Read from BlizzCon 2026 footage; ${reviewed} of ${total} ${noun} reviewed.`)
  }
  if (shaky > 0) {
    lines.push(`${shaky} of ${total} ${noun} ${shaky === 1 ? 'is' : 'are'} uncertain and marked below.`)
  }
  return lines
}


/**
 * The amber line on a single card, when one applies at all. Delegates to the
 * tooltip's own `trustLine` so a shaky racial and a shaky talent say the same
 * words; a racial has one rank and no derivation, so the rank facts are fixed
 * and only the reading can ever be in doubt. Nothing hits this today - every
 * racial was read at confidence 1.0 - and it stays because the next rebuild or
 * a replaced prior can put a trait below the threshold.
 */
export function traitTrustLine(trait: RaceTrait): string | undefined {
  return trustLine({ ranksSource: 'observed', ranksObserved: [1], maxRank: 1, source: trait.source })
}

/**
 * What a card's Details disclosure shows: when the tooltip was read, the note
 * the pipeline left when it is worth a player's time, and nothing that belongs
 * on the review route.
 */
export function traitDetailLines(trait: RaceTrait): string[] {
  const lines = [
    readingLine(trait.source),
    trait.source.reviewed ? 'Checked by a reviewer.' : undefined,
    ...playerNoteLines(trait.source.note),
  ]
  return lines.filter((l): l is string => Boolean(l) && !internalId(l!))
}

/** `h:mm:ss` into the stream, for the Details line and the crop link. */
export function traitStamp(trait: RaceTrait): string | undefined {
  return trait.source.kind === 'video' && trait.source.t !== undefined ? streamStamp(trait.source.t) : undefined
}

// --- the Classic side ------------------------------------------------------

/**
 * The one word every render of the Classic paraphrase carries. The prior
 * (`data/prior/classic-era/racials.json`) was written from memory and is flagged
 * `verified: false`; a player must never read it as game text.
 */
export const UNVERIFIED = 'unverified'

export const CLASSIC_LABEL: Record<string, string> = {
  new: 'New',
  changed: 'Changed',
  same: 'Same',
  unknown: 'Unknown',
}

/** The chip's tooltip: what the verdict means, not how it was reached. */
export function classicChipHint(status: string): string {
  switch (status) {
    case 'new':
      return 'No racial of this name existed in Classic Era.'
    case 'changed':
      return 'Classic Era had this racial and it works differently now.'
    case 'same':
      return 'Classic Era had this racial and it works the same way.'
    default:
      return 'Classic Era had a racial of this name; whether it changed was never decided.'
  }
}

/** The heading of the card behind the chip. */
export function classicCardTitle(classic: { status: string; classicName?: string }): string {
  if (classic.status === 'new') return 'Not in Classic Era'
  return classic.classicName ? `In Classic Era: ${classic.classicName}` : 'In Classic Era'
}

/**
 * `classic.note` in player words. The pipeline appends "Classic side written
 * from memory and unverified (data/prior/...)" to every verdict; the card says
 * `unverified` in its own right and must not print a repo path, so that clause
 * and anything carrying a file path are dropped and the reasoning is kept.
 */
export function classicNoteLines(note: string | undefined): string[] {
  if (!note) return []
  const out: string[] = []
  for (const raw of note.split(';')) {
    const clause = raw.trim()
    if (!clause) continue
    if (/written from memory|\bunverified\b|data\/prior/i.test(clause)) continue
    const line = withPeriod(capitalise(clause))
    if (!internalId(line) && !out.includes(line)) out.push(line)
  }
  return out
}

function capitalise(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1)
}

/**
 * `source.note` in player words, for a racial. Only two shapes occur today -
 * the class bar's separation margin, which is a pipeline number, and the lore
 * paragraph's "continues past the box edge", which is a caveat a player wants.
 */
export function playerNoteLines(note: string | undefined): string[] {
  if (!note) return []
  const out: string[] = []
  for (const raw of note.split(';')) {
    const clause = raw.trim()
    if (!clause) continue
    if (/separation margin|dhash|opencv|upscale|scroll position/i.test(clause)) continue
    const line = withPeriod(capitalise(clause))
    if (!internalId(line) && !out.includes(line)) out.push(line)
  }
  return out
}

// --- small helpers ---------------------------------------------------------

/** The fallback when a racial icon crop is missing, as in the talent grid. */
export function initials(name: string): string {
  const words = name.split(/\s+/).filter(Boolean)
  if (words.length === 0) return '?'
  if (words.length === 1) return words[0]!.slice(0, 2)
  return `${words[0]![0] ?? ''}${words[1]![0] ?? ''}`.toUpperCase()
}

export function kindLabel(kind: 'active' | 'passive'): string {
  return kind === 'active' ? 'Active' : 'Passive'
}
