/**
 * Everything `#/spells` and `#/spells/<class>` decide, as pure functions.
 *
 * The page model lives here for the same reason `racesModel.ts` does: the
 * grouping, the coverage sentence and the New chip are rules, not markup.
 * `SpellsPage.tsx` supplies the data - `spells-index.json` for the overview,
 * one class file for a class page - and computes nothing itself.
 *
 * The rules come from `docs/handover/2026-09-13-spells-data.md` section 5, and
 * the first one governs everything else:
 *
 *   1. **This is not a spell list, it is a coverage record.** It is one demo
 *      character's book at level 38, filtered by which tabs happened to be
 *      opened on stream. So the page is titled "seen on stream", the coverage
 *      sentence sits in the header rather than in a footnote, and the tabs
 *      nobody opened are named in it.
 *   3. `ranksSeen` is what was on screen, never a range: `rankLabel` lists the
 *      ranks it saw and never writes "ranks 1-4".
 *   4. A tooltip without a rank says so in words, rather than implying rank 1.
 *   7. `classic.status` is name-level only, against a list written from memory.
 *      The New chip therefore carries one caveat at the top of the page
 *      (`NEW_CAVEAT`), not a repeat on every row.
 *   8. A spell with no `tab` was read from a search page and is grouped under
 *      "Seen only in a search", not filed into an invented tab.
 */
import { displayName } from '../data/load'
import type { Spell, SpellData, SpellSource, SpellTooltip } from '../data/schema.spells'
import { spellsHash } from '../url/route'
import { initials } from './initials'
import { datasetTrustLines, readingLine, streamStamp, trustLine } from './trust'

export { initials }

// --- the index (generated by scripts/gen-data-index.mjs) -------------------

export interface IndexTab {
  id: string
  name: string
  spells: number
}

export interface IndexClass {
  id: string
  className: string
  observedLevel: number
  entries: number
  /** Entries whose full tooltip text was read. */
  withText: number
  /** Tooltips read, which is more than `withText` when one spell got two. */
  tooltips: number
  new: number
  searchOnly: number
  tabs: IndexTab[]
  tabsMissing: string[]
  showAllSpellRanks: 'on' | 'off' | 'not observed'
  complete: boolean
}

export interface AbsentClass {
  id: string
  className: string
}

export interface SpellsIndex {
  prior: string
  priorVerified: boolean
  classes: IndexClass[]
  absent: AbsentClass[]
}

// --- the overview ----------------------------------------------------------

export interface OverviewCard {
  id: string
  className: string
  entries: number
  withText: number
  new: number
  /** Tab names in spellbook order, for the "across ..." line. */
  tabs: string[]
  /** Names of the tabs nobody opened. */
  tabsMissing: string[]
  href: string
}

/** One card per class that has a spellbook file, in class order. */
export function overviewCards(index: SpellsIndex): OverviewCard[] {
  return index.classes
    .map((c) => ({
      id: c.id,
      className: c.className,
      entries: c.entries,
      withText: c.withText,
      new: c.new,
      tabs: c.tabs.map((t) => t.name),
      tabsMissing: c.tabsMissing.map(tabName),
      href: spellsHash(c.id),
    }))
    .sort((a, b) => a.className.localeCompare(b.className))
}

/** The counts under a card: what was seen, and how much of it has full text. */
export function cardCountLine(card: Pick<OverviewCard, 'entries' | 'withText'>): string {
  const entries = `${card.entries} ${card.entries === 1 ? 'entry' : 'entries'} seen`
  return card.withText === 0 ? `${entries}, none with full text` : `${entries}, ${card.withText} with full text`
}

/** What a card says about the pages nobody opened, or nothing when all were. */
export function cardGapLine(card: Pick<OverviewCard, 'tabsMissing'>): string | undefined {
  if (card.tabsMissing.length === 0) return undefined
  return `${joinNames(card.tabsMissing)} never opened`
}

/**
 * The classes with no spellbook file at all. Priest is the only one today: it
 * was never on screen in the source window, so there is nothing to show and the
 * overview has to say that instead of offering a page that 404s.
 */
export function absentLine(index: SpellsIndex): string | undefined {
  const names = index.absent.map((c) => c.className)
  if (names.length === 0) return undefined
  if (names.length === 1) {
    return `${names[0]} never appeared in the footage, so there is no ${names[0]!.toLowerCase()} page.`
  }
  return `${joinNames(names)} never appeared in the footage, so they have no page here.`
}

// --- one class -------------------------------------------------------------

/**
 * The coverage record as one sentence, in the header where rule 1 wants it:
 *
 *   "Spells seen on stream: 41 entries across Balance, Feral Combat,
 *    Restoration; 27 with full text. The General page was not shown."
 */
export function coverageLine(data: SpellData): string {
  const entries = data.spells.length
  const tabs = orderedTabs(data).map((t) => t.name)
  const where = tabs.length === 0 ? '' : tabs.length === 1 ? ` on the ${tabs[0]} page` : ` across ${tabs.join(', ')}`
  const withText = data.spells.filter(hasText).length
  const text = withText === 0 ? 'none with full text' : `${withText} with full text`
  const seen = `Spells seen on stream: ${entries} ${entries === 1 ? 'entry' : 'entries'}${where}; ${text}.`
  const missing = data.coverage.tabsMissing.map(tabName)
  if (missing.length === 0) return seen
  const pages = missing.length === 1 ? 'page was' : 'pages were'
  return `${seen} The ${joinNames(missing)} ${pages} not shown.`
}

/** The other bound on the list: the character whose book this was. */
export function levelLine(data: SpellData): string {
  return `The character was level ${data.observedLevel}, so nothing learned later is here.`
}

/** What a rank label on a row means, said once per page. */
export function ranksLine(data: SpellData): string {
  return data.coverage.showAllSpellRanks === 'on'
    ? 'The book was showing every rank, so a row can list several.'
    : "A rank is the one the book showed, not the spell's full range."
}

/**
 * The one caveat the New chip needs, at the top of the page rather than on
 * every row (rule 7). "New" is a name-level verdict against a Classic Era list
 * written from memory, so the chip means "we could not find this name", not
 * "Blizzard added this".
 */
export const NEW_CAVEAT =
  'New means the name is missing from our Classic Era list, which was written from memory and never checked. It is a hint, not a finding.'

export interface SpellGroup {
  id: string
  name: string
  spells: Spell[]
}

/** The id the search-only group carries; no tab can collide with it. */
export const SEARCH_GROUP = 'seen-only-in-a-search'

/**
 * The list grouped the way the spellbook is: one group per tab that was opened,
 * in tab order, entries in file order (alphabetical, which is the page's own
 * order). Rule 8's group comes last and is named for what it is.
 */
export function spellGroups(data: SpellData): SpellGroup[] {
  const groups = orderedTabs(data).map((tab) => ({
    id: tab.id,
    name: tab.name,
    spells: data.spells.filter((s) => s.tab === tab.id),
  }))
  const loose = data.spells.filter((s) => !s.tab || !data.tabs.some((t) => t.id === s.tab))
  if (loose.length > 0) groups.push({ id: SEARCH_GROUP, name: 'Seen only in a search', spells: loose })
  return groups.filter((g) => g.spells.length > 0)
}

/**
 * Rule 3: the ranks that were on screen, listed. Never a range - "Ranks 1-4"
 * would claim the spell has four ranks, and the data does not know that.
 */
export function rankLabel(spell: Spell): string | undefined {
  const ranks = spell.ranksSeen
  if (!ranks || ranks.length === 0) return undefined
  const sorted = [...ranks].sort((a, b) => a - b)
  return sorted.length === 1 ? `Rank ${sorted[0]}` : `Ranks ${sorted.join(', ')}`
}

/** True when the Classic Era list has no spell of this name (the New chip). */
export function isNew(spell: Spell): boolean {
  return spell.classic.status === 'new'
}

export function hasText(spell: Spell): boolean {
  return (spell.tooltips ?? []).length > 0
}

export function kindLabel(kind: Spell['kind']): string | undefined {
  if (kind === 'passive') return 'Passive'
  if (kind === 'racial') return 'Racial'
  if (kind === 'racial-passive') return 'Racial, passive'
  return undefined
}

// --- the tooltips ----------------------------------------------------------

export interface TooltipFact {
  label: string
  value: string
}

/**
 * The tooltip's own header lines, in the order the game prints them. Labels are
 * only added where the value does not carry its own ("75 Mana" needs none,
 * "Earth Totem" does).
 */
export function tooltipFacts(tooltip: SpellTooltip): TooltipFact[] {
  const facts: TooltipFact[] = []
  if (tooltip.cost) facts.push({ label: 'Cost', value: tooltip.cost })
  if (tooltip.range) facts.push({ label: 'Range', value: tooltip.range })
  if (tooltip.castTime) facts.push({ label: 'Cast', value: tooltip.castTime })
  if (tooltip.cooldown) facts.push({ label: 'Cooldown', value: tooltip.cooldown })
  if (tooltip.tools) facts.push({ label: 'Tools', value: tooltip.tools })
  for (const req of tooltip.requires ?? []) facts.push({ label: 'Requires', value: req })
  return facts
}

/**
 * Rule 4: the rank a tooltip belongs to, in words. Only 23 of 112 hovers could
 * be tied to a list row, and the rest must not be read as rank 1.
 */
export function tooltipRankLine(tooltip: SpellTooltip): string {
  return tooltip.rank === undefined
    ? 'One rank; which one was not on screen.'
    : `Rank ${tooltip.rank}, as the row next to it read.`
}

/** When the box was read, for the line under the text. */
export function tooltipReadLine(tooltip: SpellTooltip): string | undefined {
  return readingLine(tooltip.source)
}

/** `h:mm:ss` into the stream, for the link to the frame. */
export function spellStamp(source: SpellSource): string | undefined {
  return source.kind === 'video' && source.t !== undefined ? streamStamp(source.t) : undefined
}

// --- trust -----------------------------------------------------------------

/**
 * The page's source statement, made once at the top the way the races page
 * makes it: every entry here was read by the same means at the same time, so a
 * copy of the sentence on each of 63 rows would be noise rather than honesty.
 * A row that is genuinely shaky still gets its own amber line below.
 */
export function spellTrustLines(spells: Spell[]): string[] {
  return datasetTrustLines(spells, { one: 'entry', many: 'entries' })
}

/**
 * The amber line on a single row, when one applies. Delegates to the talent
 * tooltip's own `trustLine`, so a shaky spell and a shaky talent say the same
 * words: a spell row has one reading and no derived ranks, so only the reading
 * can ever be in doubt.
 */
export function spellTrustLine(spell: Spell): string | undefined {
  return trustLine({ ranksSource: 'observed', ranksObserved: [1], maxRank: 1, source: spell.source }, { short: true })
}

/**
 * `notes[]` in player words: `trust.playerNotes`, re-exported because every
 * caller and every test here already looks for it under this name. The guard
 * list it uses is the one the talent tooltip uses (code review K-24).
 */
export { playerNotes } from './trust'

// --- small helpers ---------------------------------------------------------

/** Tabs in the order the spellbook shows them, not the order they were read. */
function orderedTabs(data: SpellData) {
  return [...data.tabs].sort((a, b) => a.order - b.order)
}

/** A tab id as the game spells it: `feral-combat` -> `Feral Combat`. */
export function tabName(id: string): string {
  return displayName(id)
}

function joinNames(names: string[]): string {
  if (names.length <= 1) return names[0] ?? ''
  return `${names.slice(0, -1).join(', ')} and ${names[names.length - 1]}`
}
