/// <reference types="node" />
/**
 * classes-index.json and iconCrops.ts are generated by
 * scripts/gen-data-index.mjs and committed (tsc runs before vite in
 * `npm run build`). This fails when data/talents changed without them being
 * regenerated - vite regenerates on every dev server, build and vitest run, so
 * a failure here means the refreshed files were not committed.
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { expected } from '../../scripts/gen-data-index.mjs'
import classesIndex from './classes-index.json'
import { iconCropUrl, iconCropCount } from './iconCrop'
import { parseClass } from './schema.zod'

const here = fileURLToPath(new URL('.', import.meta.url))
const repo = join(here, '../../..')

describe('generated data indexes', () => {
  it('classes-index.json is up to date', () => {
    expect(readFileSync(join(here, 'classes-index.json'), 'utf8')).toBe(expected().index)
  })

  it('iconCrops.ts is up to date', () => {
    expect(readFileSync(join(here, 'iconCrops.ts'), 'utf8')).toBe(expected().crops)
  })

  it('indexes every class file with its trees and counts', () => {
    const ids = classesIndex.map((c) => c.id)
    expect(new Set(ids).size).toBe(ids.length)
    for (const entry of classesIndex) {
      const cls = parseClass(
        JSON.parse(readFileSync(join(repo, entry.origin === 'fixtures' ? 'web/tests/fixtures' : `data/${entry.origin}`, `${entry.id}.json`), 'utf8')),
        entry.id,
      )
      expect(entry.className).toBe(cls.className)
      expect(entry.maxPoints).toBe(cls.rules.maxPoints)
      expect(entry.talents).toBe(cls.trees.flatMap((t) => t.talents).length)
      expect(entry.trees.map((t) => t.name)).toEqual(
        [...cls.trees].sort((a, b) => a.order - b.order).map((t) => t.name),
      )
    }
  })

  it('resolves every crop icon the calculator renders, and nothing else', () => {
    expect(iconCropCount()).toBeGreaterThan(0)
    expect(iconCropUrl(undefined)).toBeUndefined()
    expect(iconCropUrl('data/review/nope/nope/nope.icon.png')).toBeUndefined()
    let seen = 0
    for (const entry of classesIndex) {
      const cls = parseClass(
        JSON.parse(readFileSync(join(repo, entry.origin === 'fixtures' ? 'web/tests/fixtures' : `data/${entry.origin}`, `${entry.id}.json`), 'utf8')),
        entry.id,
      )
      for (const tree of cls.trees) {
        for (const t of tree.talents) {
          if (t.iconSource !== 'crop') continue
          seen++
          expect(iconCropUrl(t.iconCrop), `${t.id} iconCrop ${t.iconCrop}`).toBeDefined()
          expect(iconCropUrl(`./${t.iconCrop}`)).toBe(iconCropUrl(t.iconCrop))
        }
      }
    }
    expect(seen).toBeGreaterThan(0)
    // review-only frame crops must not be in the calculator's map
    expect(iconCropUrl('data/review/paladin/holy/_header.png')).toBeUndefined()
  })
})
