/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 73 crops the calculator actually renders. The full registry of
 * every crop under data/review/ lives in crops.ts and is review-only.
 */
import c0 from '../../../data/review/druid/balance/genesis.icon.png?url'
import c1 from '../../../data/review/druid/balance/improved-wrath.icon.png?url'
import c2 from '../../../data/review/druid/balance/natures-splendor.icon.png?url'
import c3 from '../../../data/review/druid/feral-combat/feral-charge.icon.png?url'
import c4 from '../../../data/review/druid/feral-combat/king-of-the-jungle.icon.png?url'
import c5 from '../../../data/review/druid/feral-combat/mangle.icon.png?url'
import c6 from '../../../data/review/druid/restoration/natures-swiftness.icon.png?url'
import c7 from '../../../data/review/hunter/beast-mastery/deadly-aspects.icon.png?url'
import c8 from '../../../data/review/hunter/beast-mastery/endurance-training.icon.png?url'
import c9 from '../../../data/review/hunter/marksmanship/improved-stings.icon.png?url'
import c10 from '../../../data/review/hunter/marksmanship/rapid-killing.icon.png?url'
import c11 from '../../../data/review/hunter/marksmanship/sniper-shot.icon.png?url'
import c12 from '../../../data/review/hunter/survival/counterattack.icon.png?url'
import c13 from '../../../data/review/hunter/survival/deterrence.icon.png?url'
import c14 from '../../../data/review/hunter/survival/improved-wing-clip.icon.png?url'
import c15 from '../../../data/review/hunter/survival/lacerating-strikes.icon.png?url'
import c16 from '../../../data/review/hunter/survival/predators-edge.icon.png?url'
import c17 from '../../../data/review/hunter/survival/strider-kick.icon.png?url'
import c18 from '../../../data/review/hunter/survival/survival-tactics.icon.png?url'
import c19 from '../../../data/review/hunter/survival/survivalists-discipline.icon.png?url'
import c20 from '../../../data/review/mage/arcane/arcane-geometry.icon.png?url'
import c21 from '../../../data/review/mage/arcane/improved-channeling.icon.png?url'
import c22 from '../../../data/review/mage/fire/blast-wave.icon.png?url'
import c23 from '../../../data/review/mage/fire/fire-power.icon.png?url'
import c24 from '../../../data/review/mage/fire/hot-streak.icon.png?url'
import c25 from '../../../data/review/mage/fire/impact.icon.png?url'
import c26 from '../../../data/review/mage/fire/incineration.icon.png?url'
import c27 from '../../../data/review/mage/fire/master-of-elements.icon.png?url'
import c28 from '../../../data/review/mage/fire/wake-of-fire.icon.png?url'
import c29 from '../../../data/review/mage/frost/shatter.icon.png?url'
import c30 from '../../../data/review/paladin/holy/divine-favor.icon.png?url'
import c31 from '../../../data/review/paladin/holy/divine-intellect.icon.png?url'
import c32 from '../../../data/review/paladin/holy/divine-precision.icon.png?url'
import c33 from '../../../data/review/paladin/holy/improved-holy-strike.icon.png?url'
import c34 from '../../../data/review/paladin/protection/iron-creed.icon.png?url'
import c35 from '../../../data/review/paladin/protection/sacred-duty.icon.png?url'
import c36 from '../../../data/review/paladin/protection/shield-specialization.icon.png?url'
import c37 from '../../../data/review/paladin/protection/templars-bulwark.icon.png?url'
import c38 from '../../../data/review/paladin/retribution/conviction.icon.png?url'
import c39 from '../../../data/review/paladin/retribution/holy-conduit.icon.png?url'
import c40 from '../../../data/review/paladin/retribution/sacred-arbiter.icon.png?url'
import c41 from '../../../data/review/paladin/retribution/twist-of-light.icon.png?url'
import c42 from '../../../data/review/priest/discipline/power-in-light.icon.png?url'
import c43 from '../../../data/review/priest/discipline/twin-disciplines.icon.png?url'
import c44 from '../../../data/review/priest/holy/improved-renew.icon.png?url'
import c45 from '../../../data/review/priest/holy/twilight-focus.icon.png?url'
import c46 from '../../../data/review/priest/shadow-magic/devouring-contagion.icon.png?url'
import c47 from '../../../data/review/rogue/subtlety/elusiveness.icon.png?url'
import c48 from '../../../data/review/shaman/elemental-combat/concussion.icon.png?url'
import c49 from '../../../data/review/shaman/elemental-combat/convection.icon.png?url'
import c50 from '../../../data/review/shaman/elemental-combat/elemental-alacrity.icon.png?url'
import c51 from '../../../data/review/shaman/elemental-combat/elemental-devastation.icon.png?url'
import c52 from '../../../data/review/shaman/elemental-combat/elemental-reach.icon.png?url'
import c53 from '../../../data/review/shaman/enhancement/anticipation.icon.png?url'
import c54 from '../../../data/review/shaman/enhancement/guardian-totems.icon.png?url'
import c55 from '../../../data/review/shaman/enhancement/improved-lightning-shield.icon.png?url'
import c56 from '../../../data/review/shaman/restoration/improved-healing-wave.icon.png?url'
import c57 from '../../../data/review/shaman/restoration/riptide.icon.png?url'
import c58 from '../../../data/review/tinker/gadgetry/steady-hands.icon.png?url'
import c59 from '../../../data/review/warlock/affliction/drain-hope.icon.png?url'
import c60 from '../../../data/review/warlock/demonology/decimation.icon.png?url'
import c61 from '../../../data/review/warlock/demonology/demonic-aegis.icon.png?url'
import c62 from '../../../data/review/warlock/demonology/demonic-brand.icon.png?url'
import c63 from '../../../data/review/warlock/demonology/demonic-energies.icon.png?url'
import c64 from '../../../data/review/warlock/demonology/demonic-pact.icon.png?url'
import c65 from '../../../data/review/warlock/demonology/improved-sayaad.icon.png?url'
import c66 from '../../../data/review/warlock/demonology/unholy-power.icon.png?url'
import c67 from '../../../data/review/warrior/arms/improved-charge.icon.png?url'
import c68 from '../../../data/review/warrior/arms/improved-tactical-mastery.icon.png?url'
import c69 from '../../../data/review/warrior/arms/weaponmaster.icon.png?url'
import c70 from '../../../data/review/warrior/fury/blood-crazed.icon.png?url'
import c71 from '../../../data/review/warrior/fury/booming-voice.icon.png?url'
import c72 from '../../../data/review/warrior/protection/vanguard.icon.png?url'

export const iconCropUrls: Record<string, string> = {
  "data/review/druid/balance/genesis.icon.png": c0,
  "data/review/druid/balance/improved-wrath.icon.png": c1,
  "data/review/druid/balance/natures-splendor.icon.png": c2,
  "data/review/druid/feral-combat/feral-charge.icon.png": c3,
  "data/review/druid/feral-combat/king-of-the-jungle.icon.png": c4,
  "data/review/druid/feral-combat/mangle.icon.png": c5,
  "data/review/druid/restoration/natures-swiftness.icon.png": c6,
  "data/review/hunter/beast-mastery/deadly-aspects.icon.png": c7,
  "data/review/hunter/beast-mastery/endurance-training.icon.png": c8,
  "data/review/hunter/marksmanship/improved-stings.icon.png": c9,
  "data/review/hunter/marksmanship/rapid-killing.icon.png": c10,
  "data/review/hunter/marksmanship/sniper-shot.icon.png": c11,
  "data/review/hunter/survival/counterattack.icon.png": c12,
  "data/review/hunter/survival/deterrence.icon.png": c13,
  "data/review/hunter/survival/improved-wing-clip.icon.png": c14,
  "data/review/hunter/survival/lacerating-strikes.icon.png": c15,
  "data/review/hunter/survival/predators-edge.icon.png": c16,
  "data/review/hunter/survival/strider-kick.icon.png": c17,
  "data/review/hunter/survival/survival-tactics.icon.png": c18,
  "data/review/hunter/survival/survivalists-discipline.icon.png": c19,
  "data/review/mage/arcane/arcane-geometry.icon.png": c20,
  "data/review/mage/arcane/improved-channeling.icon.png": c21,
  "data/review/mage/fire/blast-wave.icon.png": c22,
  "data/review/mage/fire/fire-power.icon.png": c23,
  "data/review/mage/fire/hot-streak.icon.png": c24,
  "data/review/mage/fire/impact.icon.png": c25,
  "data/review/mage/fire/incineration.icon.png": c26,
  "data/review/mage/fire/master-of-elements.icon.png": c27,
  "data/review/mage/fire/wake-of-fire.icon.png": c28,
  "data/review/mage/frost/shatter.icon.png": c29,
  "data/review/paladin/holy/divine-favor.icon.png": c30,
  "data/review/paladin/holy/divine-intellect.icon.png": c31,
  "data/review/paladin/holy/divine-precision.icon.png": c32,
  "data/review/paladin/holy/improved-holy-strike.icon.png": c33,
  "data/review/paladin/protection/iron-creed.icon.png": c34,
  "data/review/paladin/protection/sacred-duty.icon.png": c35,
  "data/review/paladin/protection/shield-specialization.icon.png": c36,
  "data/review/paladin/protection/templars-bulwark.icon.png": c37,
  "data/review/paladin/retribution/conviction.icon.png": c38,
  "data/review/paladin/retribution/holy-conduit.icon.png": c39,
  "data/review/paladin/retribution/sacred-arbiter.icon.png": c40,
  "data/review/paladin/retribution/twist-of-light.icon.png": c41,
  "data/review/priest/discipline/power-in-light.icon.png": c42,
  "data/review/priest/discipline/twin-disciplines.icon.png": c43,
  "data/review/priest/holy/improved-renew.icon.png": c44,
  "data/review/priest/holy/twilight-focus.icon.png": c45,
  "data/review/priest/shadow-magic/devouring-contagion.icon.png": c46,
  "data/review/rogue/subtlety/elusiveness.icon.png": c47,
  "data/review/shaman/elemental-combat/concussion.icon.png": c48,
  "data/review/shaman/elemental-combat/convection.icon.png": c49,
  "data/review/shaman/elemental-combat/elemental-alacrity.icon.png": c50,
  "data/review/shaman/elemental-combat/elemental-devastation.icon.png": c51,
  "data/review/shaman/elemental-combat/elemental-reach.icon.png": c52,
  "data/review/shaman/enhancement/anticipation.icon.png": c53,
  "data/review/shaman/enhancement/guardian-totems.icon.png": c54,
  "data/review/shaman/enhancement/improved-lightning-shield.icon.png": c55,
  "data/review/shaman/restoration/improved-healing-wave.icon.png": c56,
  "data/review/shaman/restoration/riptide.icon.png": c57,
  "data/review/tinker/gadgetry/steady-hands.icon.png": c58,
  "data/review/warlock/affliction/drain-hope.icon.png": c59,
  "data/review/warlock/demonology/decimation.icon.png": c60,
  "data/review/warlock/demonology/demonic-aegis.icon.png": c61,
  "data/review/warlock/demonology/demonic-brand.icon.png": c62,
  "data/review/warlock/demonology/demonic-energies.icon.png": c63,
  "data/review/warlock/demonology/demonic-pact.icon.png": c64,
  "data/review/warlock/demonology/improved-sayaad.icon.png": c65,
  "data/review/warlock/demonology/unholy-power.icon.png": c66,
  "data/review/warrior/arms/improved-charge.icon.png": c67,
  "data/review/warrior/arms/improved-tactical-mastery.icon.png": c68,
  "data/review/warrior/arms/weaponmaster.icon.png": c69,
  "data/review/warrior/fury/blood-crazed.icon.png": c70,
  "data/review/warrior/fury/booming-voice.icon.png": c71,
  "data/review/warrior/protection/vanguard.icon.png": c72,
}
