/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 91 crops the races routes render or link: 36 px racial icons,
 * the trait row crops behind each card's Details line, and the class-bar and
 * panel evidence. The full registry of every crop under data/review/ lives in
 * crops.ts and is review-only.
 */
import r0 from '../../../data/review/races/dwarf/_classbar.png?url'
import r1 from '../../../data/review/races/dwarf/_panel.png?url'
import r2 from '../../../data/review/races/dwarf/big-game-hunter.icon.png?url'
import r3 from '../../../data/review/races/dwarf/big-game-hunter.png?url'
import r4 from '../../../data/review/races/dwarf/find-treasure.icon.png?url'
import r5 from '../../../data/review/races/dwarf/find-treasure.png?url'
import r6 from '../../../data/review/races/dwarf/mace-specialization.icon.png?url'
import r7 from '../../../data/review/races/dwarf/mace-specialization.png?url'
import r8 from '../../../data/review/races/dwarf/stoneform.icon.png?url'
import r9 from '../../../data/review/races/dwarf/stoneform.png?url'
import r10 from '../../../data/review/races/gnome/_classbar.png?url'
import r11 from '../../../data/review/races/gnome/_panel.png?url'
import r12 from '../../../data/review/races/gnome/engineering-specialization.icon.png?url'
import r13 from '../../../data/review/races/gnome/engineering-specialization.png?url'
import r14 from '../../../data/review/races/gnome/escape-artist.icon.png?url'
import r15 from '../../../data/review/races/gnome/escape-artist.png?url'
import r16 from '../../../data/review/races/gnome/eureka.icon.png?url'
import r17 from '../../../data/review/races/gnome/eureka.png?url'
import r18 from '../../../data/review/races/gnome/expansive-mind.icon.png?url'
import r19 from '../../../data/review/races/gnome/expansive-mind.png?url'
import r20 from '../../../data/review/races/human/_classbar.png?url'
import r21 from '../../../data/review/races/human/_panel.png?url'
import r22 from '../../../data/review/races/human/perception.icon.png?url'
import r23 from '../../../data/review/races/human/perception.png?url'
import r24 from '../../../data/review/races/human/sword-specialization.icon.png?url'
import r25 from '../../../data/review/races/human/sword-specialization.png?url'
import r26 from '../../../data/review/races/human/the-human-spirit.icon.png?url'
import r27 from '../../../data/review/races/human/the-human-spirit.png?url'
import r28 from '../../../data/review/races/human/will-to-survive.icon.png?url'
import r29 from '../../../data/review/races/human/will-to-survive.png?url'
import r30 from '../../../data/review/races/night-elf/_classbar.png?url'
import r31 from '../../../data/review/races/night-elf/_panel.png?url'
import r32 from '../../../data/review/races/night-elf/elunes-light.icon.png?url'
import r33 from '../../../data/review/races/night-elf/elunes-light.png?url'
import r34 from '../../../data/review/races/night-elf/quickness.icon.png?url'
import r35 from '../../../data/review/races/night-elf/quickness.png?url'
import r36 from '../../../data/review/races/night-elf/shadowmeld.icon.png?url'
import r37 from '../../../data/review/races/night-elf/shadowmeld.png?url'
import r38 from '../../../data/review/races/night-elf/wisp-spirit.icon.png?url'
import r39 from '../../../data/review/races/night-elf/wisp-spirit.png?url'
import r40 from '../../../data/review/races/orc/_classbar.png?url'
import r41 from '../../../data/review/races/orc/_panel.png?url'
import r42 from '../../../data/review/races/orc/axe-specialization.icon.png?url'
import r43 from '../../../data/review/races/orc/axe-specialization.png?url'
import r44 from '../../../data/review/races/orc/blood-fury.icon.png?url'
import r45 from '../../../data/review/races/orc/blood-fury.png?url'
import r46 from '../../../data/review/races/orc/hardiness.icon.png?url'
import r47 from '../../../data/review/races/orc/hardiness.png?url'
import r48 from '../../../data/review/races/orc/shatter-curse.icon.png?url'
import r49 from '../../../data/review/races/orc/shatter-curse.png?url'
import r50 from '../../../data/review/races/skyborne/_classbar.png?url'
import r51 from '../../../data/review/races/skyborne/elemental-insight.icon.png?url'
import r52 from '../../../data/review/races/skyborne/elemental-insight.png?url'
import r53 from '../../../data/review/races/skyborne/read-ley-line.icon.png?url'
import r54 from '../../../data/review/races/skyborne/read-ley-line.png?url'
import r55 from '../../../data/review/races/skyborne/skysight.icon.png?url'
import r56 from '../../../data/review/races/skyborne/skysight.png?url'
import r57 from '../../../data/review/races/skyborne/walk-on-air.icon.png?url'
import r58 from '../../../data/review/races/skyborne/walk-on-air.png?url'
import r59 from '../../../data/review/races/skyborne/wind-blessed.icon.png?url'
import r60 from '../../../data/review/races/skyborne/wind-blessed.png?url'
import r61 from '../../../data/review/races/tauren/_classbar.png?url'
import r62 from '../../../data/review/races/tauren/_panel.png?url'
import r63 from '../../../data/review/races/tauren/cultivation.icon.png?url'
import r64 from '../../../data/review/races/tauren/cultivation.png?url'
import r65 from '../../../data/review/races/tauren/endurance.icon.png?url'
import r66 from '../../../data/review/races/tauren/endurance.png?url'
import r67 from '../../../data/review/races/tauren/plainsrunning.icon.png?url'
import r68 from '../../../data/review/races/tauren/plainsrunning.png?url'
import r69 from '../../../data/review/races/tauren/war-stomp.icon.png?url'
import r70 from '../../../data/review/races/tauren/war-stomp.png?url'
import r71 from '../../../data/review/races/troll/_classbar.png?url'
import r72 from '../../../data/review/races/troll/_panel.png?url'
import r73 from '../../../data/review/races/troll/beast-slaying.icon.png?url'
import r74 from '../../../data/review/races/troll/beast-slaying.png?url'
import r75 from '../../../data/review/races/troll/berserking.icon.png?url'
import r76 from '../../../data/review/races/troll/berserking.png?url'
import r77 from '../../../data/review/races/troll/rapid-regeneration.icon.png?url'
import r78 from '../../../data/review/races/troll/rapid-regeneration.png?url'
import r79 from '../../../data/review/races/troll/regeneration.icon.png?url'
import r80 from '../../../data/review/races/troll/regeneration.png?url'
import r81 from '../../../data/review/races/undead/_classbar.png?url'
import r82 from '../../../data/review/races/undead/_panel.png?url'
import r83 from '../../../data/review/races/undead/cannibalize.icon.png?url'
import r84 from '../../../data/review/races/undead/cannibalize.png?url'
import r85 from '../../../data/review/races/undead/touch-of-the-grave.icon.png?url'
import r86 from '../../../data/review/races/undead/touch-of-the-grave.png?url'
import r87 from '../../../data/review/races/undead/underwater-breathing.icon.png?url'
import r88 from '../../../data/review/races/undead/underwater-breathing.png?url'
import r89 from '../../../data/review/races/undead/will-of-the-forsaken.icon.png?url'
import r90 from '../../../data/review/races/undead/will-of-the-forsaken.png?url'

export const raceCropUrls: Record<string, string> = {
  "data/review/races/dwarf/_classbar.png": r0,
  "data/review/races/dwarf/_panel.png": r1,
  "data/review/races/dwarf/big-game-hunter.icon.png": r2,
  "data/review/races/dwarf/big-game-hunter.png": r3,
  "data/review/races/dwarf/find-treasure.icon.png": r4,
  "data/review/races/dwarf/find-treasure.png": r5,
  "data/review/races/dwarf/mace-specialization.icon.png": r6,
  "data/review/races/dwarf/mace-specialization.png": r7,
  "data/review/races/dwarf/stoneform.icon.png": r8,
  "data/review/races/dwarf/stoneform.png": r9,
  "data/review/races/gnome/_classbar.png": r10,
  "data/review/races/gnome/_panel.png": r11,
  "data/review/races/gnome/engineering-specialization.icon.png": r12,
  "data/review/races/gnome/engineering-specialization.png": r13,
  "data/review/races/gnome/escape-artist.icon.png": r14,
  "data/review/races/gnome/escape-artist.png": r15,
  "data/review/races/gnome/eureka.icon.png": r16,
  "data/review/races/gnome/eureka.png": r17,
  "data/review/races/gnome/expansive-mind.icon.png": r18,
  "data/review/races/gnome/expansive-mind.png": r19,
  "data/review/races/human/_classbar.png": r20,
  "data/review/races/human/_panel.png": r21,
  "data/review/races/human/perception.icon.png": r22,
  "data/review/races/human/perception.png": r23,
  "data/review/races/human/sword-specialization.icon.png": r24,
  "data/review/races/human/sword-specialization.png": r25,
  "data/review/races/human/the-human-spirit.icon.png": r26,
  "data/review/races/human/the-human-spirit.png": r27,
  "data/review/races/human/will-to-survive.icon.png": r28,
  "data/review/races/human/will-to-survive.png": r29,
  "data/review/races/night-elf/_classbar.png": r30,
  "data/review/races/night-elf/_panel.png": r31,
  "data/review/races/night-elf/elunes-light.icon.png": r32,
  "data/review/races/night-elf/elunes-light.png": r33,
  "data/review/races/night-elf/quickness.icon.png": r34,
  "data/review/races/night-elf/quickness.png": r35,
  "data/review/races/night-elf/shadowmeld.icon.png": r36,
  "data/review/races/night-elf/shadowmeld.png": r37,
  "data/review/races/night-elf/wisp-spirit.icon.png": r38,
  "data/review/races/night-elf/wisp-spirit.png": r39,
  "data/review/races/orc/_classbar.png": r40,
  "data/review/races/orc/_panel.png": r41,
  "data/review/races/orc/axe-specialization.icon.png": r42,
  "data/review/races/orc/axe-specialization.png": r43,
  "data/review/races/orc/blood-fury.icon.png": r44,
  "data/review/races/orc/blood-fury.png": r45,
  "data/review/races/orc/hardiness.icon.png": r46,
  "data/review/races/orc/hardiness.png": r47,
  "data/review/races/orc/shatter-curse.icon.png": r48,
  "data/review/races/orc/shatter-curse.png": r49,
  "data/review/races/skyborne/_classbar.png": r50,
  "data/review/races/skyborne/elemental-insight.icon.png": r51,
  "data/review/races/skyborne/elemental-insight.png": r52,
  "data/review/races/skyborne/read-ley-line.icon.png": r53,
  "data/review/races/skyborne/read-ley-line.png": r54,
  "data/review/races/skyborne/skysight.icon.png": r55,
  "data/review/races/skyborne/skysight.png": r56,
  "data/review/races/skyborne/walk-on-air.icon.png": r57,
  "data/review/races/skyborne/walk-on-air.png": r58,
  "data/review/races/skyborne/wind-blessed.icon.png": r59,
  "data/review/races/skyborne/wind-blessed.png": r60,
  "data/review/races/tauren/_classbar.png": r61,
  "data/review/races/tauren/_panel.png": r62,
  "data/review/races/tauren/cultivation.icon.png": r63,
  "data/review/races/tauren/cultivation.png": r64,
  "data/review/races/tauren/endurance.icon.png": r65,
  "data/review/races/tauren/endurance.png": r66,
  "data/review/races/tauren/plainsrunning.icon.png": r67,
  "data/review/races/tauren/plainsrunning.png": r68,
  "data/review/races/tauren/war-stomp.icon.png": r69,
  "data/review/races/tauren/war-stomp.png": r70,
  "data/review/races/troll/_classbar.png": r71,
  "data/review/races/troll/_panel.png": r72,
  "data/review/races/troll/beast-slaying.icon.png": r73,
  "data/review/races/troll/beast-slaying.png": r74,
  "data/review/races/troll/berserking.icon.png": r75,
  "data/review/races/troll/berserking.png": r76,
  "data/review/races/troll/rapid-regeneration.icon.png": r77,
  "data/review/races/troll/rapid-regeneration.png": r78,
  "data/review/races/troll/regeneration.icon.png": r79,
  "data/review/races/troll/regeneration.png": r80,
  "data/review/races/undead/_classbar.png": r81,
  "data/review/races/undead/_panel.png": r82,
  "data/review/races/undead/cannibalize.icon.png": r83,
  "data/review/races/undead/cannibalize.png": r84,
  "data/review/races/undead/touch-of-the-grave.icon.png": r85,
  "data/review/races/undead/touch-of-the-grave.png": r86,
  "data/review/races/undead/underwater-breathing.icon.png": r87,
  "data/review/races/undead/underwater-breathing.png": r88,
  "data/review/races/undead/will-of-the-forsaken.icon.png": r89,
  "data/review/races/undead/will-of-the-forsaken.png": r90,
}
