/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 10 crops the warlock spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/warlock/armor-proficiency.icon.png?url'
import s1 from '../../../../data/review/spells/warlock/attack.icon.png?url'
import s2 from '../../../../data/review/spells/warlock/axe-specialization.icon.png?url'
import s3 from '../../../../data/review/spells/warlock/bane-of-agony.icon.png?url'
import s4 from '../../../../data/review/spells/warlock/blood-fury.icon.png?url'
import s5 from '../../../../data/review/spells/warlock/dodge.icon.png?url'
import s6 from '../../../../data/review/spells/warlock/hardiness.icon.png?url'
import s7 from '../../../../data/review/spells/warlock/languages.icon.png?url'
import s8 from '../../../../data/review/spells/warlock/shatter-curse.icon.png?url'
import s9 from '../../../../data/review/spells/warlock/shoot.icon.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/warlock/armor-proficiency.icon.png": s0,
  "data/review/spells/warlock/attack.icon.png": s1,
  "data/review/spells/warlock/axe-specialization.icon.png": s2,
  "data/review/spells/warlock/bane-of-agony.icon.png": s3,
  "data/review/spells/warlock/blood-fury.icon.png": s4,
  "data/review/spells/warlock/dodge.icon.png": s5,
  "data/review/spells/warlock/hardiness.icon.png": s6,
  "data/review/spells/warlock/languages.icon.png": s7,
  "data/review/spells/warlock/shatter-curse.icon.png": s8,
  "data/review/spells/warlock/shoot.icon.png": s9,
}
