/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 54 crops the paladin spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/paladin/armor-proficiency.icon.png?url'
import s1 from '../../../../data/review/spells/paladin/attack.icon.png?url'
import s2 from '../../../../data/review/spells/paladin/blessing-of-freedom.icon.png?url'
import s3 from '../../../../data/review/spells/paladin/blessing-of-freedom.tooltip.png?url'
import s4 from '../../../../data/review/spells/paladin/blessing-of-kings.icon.png?url'
import s5 from '../../../../data/review/spells/paladin/blessing-of-might.icon.png?url'
import s6 from '../../../../data/review/spells/paladin/blessing-of-protection.icon.png?url'
import s7 from '../../../../data/review/spells/paladin/blessing-of-salvation.icon.png?url'
import s8 from '../../../../data/review/spells/paladin/blessing-of-salvation.tooltip.png?url'
import s9 from '../../../../data/review/spells/paladin/blessing-of-wisdom.icon.png?url'
import s10 from '../../../../data/review/spells/paladin/block.icon.png?url'
import s11 from '../../../../data/review/spells/paladin/cannibalize.icon.png?url'
import s12 from '../../../../data/review/spells/paladin/concentration-aura.icon.png?url'
import s13 from '../../../../data/review/spells/paladin/consecration.icon.png?url'
import s14 from '../../../../data/review/spells/paladin/devotion-aura.icon.png?url'
import s15 from '../../../../data/review/spells/paladin/divine-intervention.icon.png?url'
import s16 from '../../../../data/review/spells/paladin/divine-protection.icon.png?url'
import s17 from '../../../../data/review/spells/paladin/divine-shield.icon.png?url'
import s18 from '../../../../data/review/spells/paladin/dodge.icon.png?url'
import s19 from '../../../../data/review/spells/paladin/exorcism.icon.png?url'
import s20 from '../../../../data/review/spells/paladin/exorcism.r3.tooltip.png?url'
import s21 from '../../../../data/review/spells/paladin/fire-resistance-aura.icon.png?url'
import s22 from '../../../../data/review/spells/paladin/flash-of-light.icon.png?url'
import s23 from '../../../../data/review/spells/paladin/frost-resistance-aura.icon.png?url'
import s24 from '../../../../data/review/spells/paladin/hammer-of-justice.icon.png?url'
import s25 from '../../../../data/review/spells/paladin/holy-light.icon.png?url'
import s26 from '../../../../data/review/spells/paladin/holy-strike.icon.png?url'
import s27 from '../../../../data/review/spells/paladin/judgement.icon.png?url'
import s28 from '../../../../data/review/spells/paladin/languages.icon.png?url'
import s29 from '../../../../data/review/spells/paladin/lay-on-hands.icon.png?url'
import s30 from '../../../../data/review/spells/paladin/parry.icon.png?url'
import s31 from '../../../../data/review/spells/paladin/perception.icon.png?url'
import s32 from '../../../../data/review/spells/paladin/purify.icon.png?url'
import s33 from '../../../../data/review/spells/paladin/redemption.icon.png?url'
import s34 from '../../../../data/review/spells/paladin/retribution-aura.icon.png?url'
import s35 from '../../../../data/review/spells/paladin/righteous-fury.icon.png?url'
import s36 from '../../../../data/review/spells/paladin/righteous-fury.tooltip.png?url'
import s37 from '../../../../data/review/spells/paladin/seal-of-fury.icon.png?url'
import s38 from '../../../../data/review/spells/paladin/seal-of-justice.icon.png?url'
import s39 from '../../../../data/review/spells/paladin/seal-of-justice.tooltip.png?url'
import s40 from '../../../../data/review/spells/paladin/seal-of-light.icon.png?url'
import s41 from '../../../../data/review/spells/paladin/seal-of-righteousness.icon.png?url'
import s42 from '../../../../data/review/spells/paladin/seal-of-the-crusader.icon.png?url'
import s43 from '../../../../data/review/spells/paladin/seal-of-the-crusader.r3.tooltip.png?url'
import s44 from '../../../../data/review/spells/paladin/seal-of-wisdom.icon.png?url'
import s45 from '../../../../data/review/spells/paladin/sense-undead.icon.png?url'
import s46 from '../../../../data/review/spells/paladin/shadow-resistance-aura.icon.png?url'
import s47 from '../../../../data/review/spells/paladin/sword-specialization.icon.png?url'
import s48 from '../../../../data/review/spells/paladin/the-human-spirit.icon.png?url'
import s49 from '../../../../data/review/spells/paladin/touch-of-the-grave.icon.png?url'
import s50 from '../../../../data/review/spells/paladin/turn-undead.icon.png?url'
import s51 from '../../../../data/review/spells/paladin/underwater-breathing.icon.png?url'
import s52 from '../../../../data/review/spells/paladin/will-of-the-forsaken.icon.png?url'
import s53 from '../../../../data/review/spells/paladin/will-to-survive.icon.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/paladin/armor-proficiency.icon.png": s0,
  "data/review/spells/paladin/attack.icon.png": s1,
  "data/review/spells/paladin/blessing-of-freedom.icon.png": s2,
  "data/review/spells/paladin/blessing-of-freedom.tooltip.png": s3,
  "data/review/spells/paladin/blessing-of-kings.icon.png": s4,
  "data/review/spells/paladin/blessing-of-might.icon.png": s5,
  "data/review/spells/paladin/blessing-of-protection.icon.png": s6,
  "data/review/spells/paladin/blessing-of-salvation.icon.png": s7,
  "data/review/spells/paladin/blessing-of-salvation.tooltip.png": s8,
  "data/review/spells/paladin/blessing-of-wisdom.icon.png": s9,
  "data/review/spells/paladin/block.icon.png": s10,
  "data/review/spells/paladin/cannibalize.icon.png": s11,
  "data/review/spells/paladin/concentration-aura.icon.png": s12,
  "data/review/spells/paladin/consecration.icon.png": s13,
  "data/review/spells/paladin/devotion-aura.icon.png": s14,
  "data/review/spells/paladin/divine-intervention.icon.png": s15,
  "data/review/spells/paladin/divine-protection.icon.png": s16,
  "data/review/spells/paladin/divine-shield.icon.png": s17,
  "data/review/spells/paladin/dodge.icon.png": s18,
  "data/review/spells/paladin/exorcism.icon.png": s19,
  "data/review/spells/paladin/exorcism.r3.tooltip.png": s20,
  "data/review/spells/paladin/fire-resistance-aura.icon.png": s21,
  "data/review/spells/paladin/flash-of-light.icon.png": s22,
  "data/review/spells/paladin/frost-resistance-aura.icon.png": s23,
  "data/review/spells/paladin/hammer-of-justice.icon.png": s24,
  "data/review/spells/paladin/holy-light.icon.png": s25,
  "data/review/spells/paladin/holy-strike.icon.png": s26,
  "data/review/spells/paladin/judgement.icon.png": s27,
  "data/review/spells/paladin/languages.icon.png": s28,
  "data/review/spells/paladin/lay-on-hands.icon.png": s29,
  "data/review/spells/paladin/parry.icon.png": s30,
  "data/review/spells/paladin/perception.icon.png": s31,
  "data/review/spells/paladin/purify.icon.png": s32,
  "data/review/spells/paladin/redemption.icon.png": s33,
  "data/review/spells/paladin/retribution-aura.icon.png": s34,
  "data/review/spells/paladin/righteous-fury.icon.png": s35,
  "data/review/spells/paladin/righteous-fury.tooltip.png": s36,
  "data/review/spells/paladin/seal-of-fury.icon.png": s37,
  "data/review/spells/paladin/seal-of-justice.icon.png": s38,
  "data/review/spells/paladin/seal-of-justice.tooltip.png": s39,
  "data/review/spells/paladin/seal-of-light.icon.png": s40,
  "data/review/spells/paladin/seal-of-righteousness.icon.png": s41,
  "data/review/spells/paladin/seal-of-the-crusader.icon.png": s42,
  "data/review/spells/paladin/seal-of-the-crusader.r3.tooltip.png": s43,
  "data/review/spells/paladin/seal-of-wisdom.icon.png": s44,
  "data/review/spells/paladin/sense-undead.icon.png": s45,
  "data/review/spells/paladin/shadow-resistance-aura.icon.png": s46,
  "data/review/spells/paladin/sword-specialization.icon.png": s47,
  "data/review/spells/paladin/the-human-spirit.icon.png": s48,
  "data/review/spells/paladin/touch-of-the-grave.icon.png": s49,
  "data/review/spells/paladin/turn-undead.icon.png": s50,
  "data/review/spells/paladin/underwater-breathing.icon.png": s51,
  "data/review/spells/paladin/will-of-the-forsaken.icon.png": s52,
  "data/review/spells/paladin/will-to-survive.icon.png": s53,
}
