/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 46 crops the warrior spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/warrior/armor-proficiency.icon.png?url'
import s1 from '../../../../data/review/spells/warrior/attack.icon.png?url'
import s2 from '../../../../data/review/spells/warrior/battle-shout.icon.png?url'
import s3 from '../../../../data/review/spells/warrior/battle-stance.icon.png?url'
import s4 from '../../../../data/review/spells/warrior/berserker-rage.icon.png?url'
import s5 from '../../../../data/review/spells/warrior/berserker-stance.icon.png?url'
import s6 from '../../../../data/review/spells/warrior/block.icon.png?url'
import s7 from '../../../../data/review/spells/warrior/bloodrage.icon.png?url'
import s8 from '../../../../data/review/spells/warrior/challenging-shout.icon.png?url'
import s9 from '../../../../data/review/spells/warrior/charge.icon.png?url'
import s10 from '../../../../data/review/spells/warrior/cleave.icon.png?url'
import s11 from '../../../../data/review/spells/warrior/defensive-stance.icon.png?url'
import s12 from '../../../../data/review/spells/warrior/demoralizing-shout.icon.png?url'
import s13 from '../../../../data/review/spells/warrior/disarm.icon.png?url'
import s14 from '../../../../data/review/spells/warrior/dodge.icon.png?url'
import s15 from '../../../../data/review/spells/warrior/dual-wield.icon.png?url'
import s16 from '../../../../data/review/spells/warrior/elemental-insight.icon.png?url'
import s17 from '../../../../data/review/spells/warrior/execute.icon.png?url'
import s18 from '../../../../data/review/spells/warrior/hamstring.icon.png?url'
import s19 from '../../../../data/review/spells/warrior/heroic-strike.icon.png?url'
import s20 from '../../../../data/review/spells/warrior/intimidating-shout.icon.png?url'
import s21 from '../../../../data/review/spells/warrior/languages.icon.png?url'
import s22 from '../../../../data/review/spells/warrior/mocking-blow.icon.png?url'
import s23 from '../../../../data/review/spells/warrior/overpower.icon.png?url'
import s24 from '../../../../data/review/spells/warrior/parry.icon.png?url'
import s25 from '../../../../data/review/spells/warrior/read-ley-line.icon.png?url'
import s26 from '../../../../data/review/spells/warrior/rend.icon.png?url'
import s27 from '../../../../data/review/spells/warrior/retaliation.icon.png?url'
import s28 from '../../../../data/review/spells/warrior/revenge.icon.png?url'
import s29 from '../../../../data/review/spells/warrior/shield-bash.icon.png?url'
import s30 from '../../../../data/review/spells/warrior/shield-block.icon.png?url'
import s31 from '../../../../data/review/spells/warrior/shield-wall.icon.png?url'
import s32 from '../../../../data/review/spells/warrior/shoot-bow.icon.png?url'
import s33 from '../../../../data/review/spells/warrior/shoot-crossbow.icon.png?url'
import s34 from '../../../../data/review/spells/warrior/shoot-gun.icon.png?url'
import s35 from '../../../../data/review/spells/warrior/slam.icon.png?url'
import s36 from '../../../../data/review/spells/warrior/sunder-armor.icon.png?url'
import s37 from '../../../../data/review/spells/warrior/tactical-mastery.icon.png?url'
import s38 from '../../../../data/review/spells/warrior/taunt.icon.png?url'
import s39 from '../../../../data/review/spells/warrior/throw.icon.png?url'
import s40 from '../../../../data/review/spells/warrior/thunder-clap.icon.png?url'
import s41 from '../../../../data/review/spells/warrior/victory-rush.icon.png?url'
import s42 from '../../../../data/review/spells/warrior/walk-on-air.icon.png?url'
import s43 from '../../../../data/review/spells/warrior/whirlwind.icon.png?url'
import s44 from '../../../../data/review/spells/warrior/whirlwind.tooltip.png?url'
import s45 from '../../../../data/review/spells/warrior/wind-blessed.icon.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/warrior/armor-proficiency.icon.png": s0,
  "data/review/spells/warrior/attack.icon.png": s1,
  "data/review/spells/warrior/battle-shout.icon.png": s2,
  "data/review/spells/warrior/battle-stance.icon.png": s3,
  "data/review/spells/warrior/berserker-rage.icon.png": s4,
  "data/review/spells/warrior/berserker-stance.icon.png": s5,
  "data/review/spells/warrior/block.icon.png": s6,
  "data/review/spells/warrior/bloodrage.icon.png": s7,
  "data/review/spells/warrior/challenging-shout.icon.png": s8,
  "data/review/spells/warrior/charge.icon.png": s9,
  "data/review/spells/warrior/cleave.icon.png": s10,
  "data/review/spells/warrior/defensive-stance.icon.png": s11,
  "data/review/spells/warrior/demoralizing-shout.icon.png": s12,
  "data/review/spells/warrior/disarm.icon.png": s13,
  "data/review/spells/warrior/dodge.icon.png": s14,
  "data/review/spells/warrior/dual-wield.icon.png": s15,
  "data/review/spells/warrior/elemental-insight.icon.png": s16,
  "data/review/spells/warrior/execute.icon.png": s17,
  "data/review/spells/warrior/hamstring.icon.png": s18,
  "data/review/spells/warrior/heroic-strike.icon.png": s19,
  "data/review/spells/warrior/intimidating-shout.icon.png": s20,
  "data/review/spells/warrior/languages.icon.png": s21,
  "data/review/spells/warrior/mocking-blow.icon.png": s22,
  "data/review/spells/warrior/overpower.icon.png": s23,
  "data/review/spells/warrior/parry.icon.png": s24,
  "data/review/spells/warrior/read-ley-line.icon.png": s25,
  "data/review/spells/warrior/rend.icon.png": s26,
  "data/review/spells/warrior/retaliation.icon.png": s27,
  "data/review/spells/warrior/revenge.icon.png": s28,
  "data/review/spells/warrior/shield-bash.icon.png": s29,
  "data/review/spells/warrior/shield-block.icon.png": s30,
  "data/review/spells/warrior/shield-wall.icon.png": s31,
  "data/review/spells/warrior/shoot-bow.icon.png": s32,
  "data/review/spells/warrior/shoot-crossbow.icon.png": s33,
  "data/review/spells/warrior/shoot-gun.icon.png": s34,
  "data/review/spells/warrior/slam.icon.png": s35,
  "data/review/spells/warrior/sunder-armor.icon.png": s36,
  "data/review/spells/warrior/tactical-mastery.icon.png": s37,
  "data/review/spells/warrior/taunt.icon.png": s38,
  "data/review/spells/warrior/throw.icon.png": s39,
  "data/review/spells/warrior/thunder-clap.icon.png": s40,
  "data/review/spells/warrior/victory-rush.icon.png": s41,
  "data/review/spells/warrior/walk-on-air.icon.png": s42,
  "data/review/spells/warrior/whirlwind.icon.png": s43,
  "data/review/spells/warrior/whirlwind.tooltip.png": s44,
  "data/review/spells/warrior/wind-blessed.icon.png": s45,
}
