/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 76 crops the druid spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/druid/abolish-poison.icon.png?url'
import s1 from '../../../../data/review/spells/druid/aquatic-form.icon.png?url'
import s2 from '../../../../data/review/spells/druid/armor-proficiency.icon.png?url'
import s3 from '../../../../data/review/spells/druid/attack.icon.png?url'
import s4 from '../../../../data/review/spells/druid/bash.icon.png?url'
import s5 from '../../../../data/review/spells/druid/bash.r2.tooltip.png?url'
import s6 from '../../../../data/review/spells/druid/bear-form.icon.png?url'
import s7 from '../../../../data/review/spells/druid/cat-form.icon.png?url'
import s8 from '../../../../data/review/spells/druid/cat-form.tooltip.png?url'
import s9 from '../../../../data/review/spells/druid/challenging-roar.icon.png?url'
import s10 from '../../../../data/review/spells/druid/challenging-roar.tooltip.png?url'
import s11 from '../../../../data/review/spells/druid/claw.icon.png?url'
import s12 from '../../../../data/review/spells/druid/claw.tooltip.png?url'
import s13 from '../../../../data/review/spells/druid/cower.tooltip.png?url'
import s14 from '../../../../data/review/spells/druid/dash.icon.png?url'
import s15 from '../../../../data/review/spells/druid/demoralizing-roar.icon.png?url'
import s16 from '../../../../data/review/spells/druid/demoralizing-roar.r3.tooltip.png?url'
import s17 from '../../../../data/review/spells/druid/dodge.icon.png?url'
import s18 from '../../../../data/review/spells/druid/elemental-insight.icon.png?url'
import s19 from '../../../../data/review/spells/druid/elemental-insight.tooltip.png?url'
import s20 from '../../../../data/review/spells/druid/enrage.icon.png?url'
import s21 from '../../../../data/review/spells/druid/enrage.tooltip.png?url'
import s22 from '../../../../data/review/spells/druid/entangling-roots.icon.png?url'
import s23 from '../../../../data/review/spells/druid/faerie-fire.icon.png?url'
import s24 from '../../../../data/review/spells/druid/ferocious-bite.icon.png?url'
import s25 from '../../../../data/review/spells/druid/ferocious-bite.r1.tooltip.png?url'
import s26 from '../../../../data/review/spells/druid/frenzied-regeneration.icon.png?url'
import s27 from '../../../../data/review/spells/druid/frenzied-regeneration.tooltip.png?url'
import s28 from '../../../../data/review/spells/druid/growl.icon.png?url'
import s29 from '../../../../data/review/spells/druid/growl.tooltip.png?url'
import s30 from '../../../../data/review/spells/druid/healing-touch.icon.png?url'
import s31 from '../../../../data/review/spells/druid/healing-touch.tooltip.png?url'
import s32 from '../../../../data/review/spells/druid/hibernate.icon.png?url'
import s33 from '../../../../data/review/spells/druid/hibernate.tooltip.png?url'
import s34 from '../../../../data/review/spells/druid/languages.icon.png?url'
import s35 from '../../../../data/review/spells/druid/mark-of-the-wild.icon.png?url'
import s36 from '../../../../data/review/spells/druid/mark-of-the-wild.tooltip.png?url'
import s37 from '../../../../data/review/spells/druid/maul.icon.png?url'
import s38 from '../../../../data/review/spells/druid/maul.tooltip.png?url'
import s39 from '../../../../data/review/spells/druid/moonfire.icon.png?url'
import s40 from '../../../../data/review/spells/druid/moonfire.tooltip.png?url'
import s41 from '../../../../data/review/spells/druid/natures-grasp.icon.png?url'
import s42 from '../../../../data/review/spells/druid/omen-of-clarity.icon.png?url'
import s43 from '../../../../data/review/spells/druid/omen-of-clarity.tooltip.png?url'
import s44 from '../../../../data/review/spells/druid/pounce.icon.png?url'
import s45 from '../../../../data/review/spells/druid/prowl.icon.png?url'
import s46 from '../../../../data/review/spells/druid/prowl.tooltip.png?url'
import s47 from '../../../../data/review/spells/druid/rake.icon.png?url'
import s48 from '../../../../data/review/spells/druid/rake.tooltip.png?url'
import s49 from '../../../../data/review/spells/druid/ravage.icon.png?url'
import s50 from '../../../../data/review/spells/druid/rebirth.icon.png?url'
import s51 from '../../../../data/review/spells/druid/regrowth.icon.png?url'
import s52 from '../../../../data/review/spells/druid/regrowth.tooltip.png?url'
import s53 from '../../../../data/review/spells/druid/rejuvenation.icon.png?url'
import s54 from '../../../../data/review/spells/druid/rejuvenation.tooltip.png?url'
import s55 from '../../../../data/review/spells/druid/remove-curse.icon.png?url'
import s56 from '../../../../data/review/spells/druid/remove-curse.tooltip.png?url'
import s57 from '../../../../data/review/spells/druid/revive.icon.png?url'
import s58 from '../../../../data/review/spells/druid/revive.r3.tooltip.png?url'
import s59 from '../../../../data/review/spells/druid/rip.icon.png?url'
import s60 from '../../../../data/review/spells/druid/shred.icon.png?url'
import s61 from '../../../../data/review/spells/druid/skysight.icon.png?url'
import s62 from '../../../../data/review/spells/druid/soothe-animal.icon.png?url'
import s63 from '../../../../data/review/spells/druid/soothe-animal.tooltip.png?url'
import s64 from '../../../../data/review/spells/druid/starfire.icon.png?url'
import s65 from '../../../../data/review/spells/druid/starfire.tooltip.png?url'
import s66 from '../../../../data/review/spells/druid/swipe.icon.png?url'
import s67 from '../../../../data/review/spells/druid/thorns.icon.png?url'
import s68 from '../../../../data/review/spells/druid/thorns.tooltip.png?url'
import s69 from '../../../../data/review/spells/druid/tranquility.icon.png?url'
import s70 from '../../../../data/review/spells/druid/tranquility.r1.tooltip.png?url'
import s71 from '../../../../data/review/spells/druid/walk-on-air.icon.png?url'
import s72 from '../../../../data/review/spells/druid/walk-on-air.tooltip.png?url'
import s73 from '../../../../data/review/spells/druid/wind-blessed.icon.png?url'
import s74 from '../../../../data/review/spells/druid/wrath.icon.png?url'
import s75 from '../../../../data/review/spells/druid/wrath.r6.tooltip.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/druid/abolish-poison.icon.png": s0,
  "data/review/spells/druid/aquatic-form.icon.png": s1,
  "data/review/spells/druid/armor-proficiency.icon.png": s2,
  "data/review/spells/druid/attack.icon.png": s3,
  "data/review/spells/druid/bash.icon.png": s4,
  "data/review/spells/druid/bash.r2.tooltip.png": s5,
  "data/review/spells/druid/bear-form.icon.png": s6,
  "data/review/spells/druid/cat-form.icon.png": s7,
  "data/review/spells/druid/cat-form.tooltip.png": s8,
  "data/review/spells/druid/challenging-roar.icon.png": s9,
  "data/review/spells/druid/challenging-roar.tooltip.png": s10,
  "data/review/spells/druid/claw.icon.png": s11,
  "data/review/spells/druid/claw.tooltip.png": s12,
  "data/review/spells/druid/cower.tooltip.png": s13,
  "data/review/spells/druid/dash.icon.png": s14,
  "data/review/spells/druid/demoralizing-roar.icon.png": s15,
  "data/review/spells/druid/demoralizing-roar.r3.tooltip.png": s16,
  "data/review/spells/druid/dodge.icon.png": s17,
  "data/review/spells/druid/elemental-insight.icon.png": s18,
  "data/review/spells/druid/elemental-insight.tooltip.png": s19,
  "data/review/spells/druid/enrage.icon.png": s20,
  "data/review/spells/druid/enrage.tooltip.png": s21,
  "data/review/spells/druid/entangling-roots.icon.png": s22,
  "data/review/spells/druid/faerie-fire.icon.png": s23,
  "data/review/spells/druid/ferocious-bite.icon.png": s24,
  "data/review/spells/druid/ferocious-bite.r1.tooltip.png": s25,
  "data/review/spells/druid/frenzied-regeneration.icon.png": s26,
  "data/review/spells/druid/frenzied-regeneration.tooltip.png": s27,
  "data/review/spells/druid/growl.icon.png": s28,
  "data/review/spells/druid/growl.tooltip.png": s29,
  "data/review/spells/druid/healing-touch.icon.png": s30,
  "data/review/spells/druid/healing-touch.tooltip.png": s31,
  "data/review/spells/druid/hibernate.icon.png": s32,
  "data/review/spells/druid/hibernate.tooltip.png": s33,
  "data/review/spells/druid/languages.icon.png": s34,
  "data/review/spells/druid/mark-of-the-wild.icon.png": s35,
  "data/review/spells/druid/mark-of-the-wild.tooltip.png": s36,
  "data/review/spells/druid/maul.icon.png": s37,
  "data/review/spells/druid/maul.tooltip.png": s38,
  "data/review/spells/druid/moonfire.icon.png": s39,
  "data/review/spells/druid/moonfire.tooltip.png": s40,
  "data/review/spells/druid/natures-grasp.icon.png": s41,
  "data/review/spells/druid/omen-of-clarity.icon.png": s42,
  "data/review/spells/druid/omen-of-clarity.tooltip.png": s43,
  "data/review/spells/druid/pounce.icon.png": s44,
  "data/review/spells/druid/prowl.icon.png": s45,
  "data/review/spells/druid/prowl.tooltip.png": s46,
  "data/review/spells/druid/rake.icon.png": s47,
  "data/review/spells/druid/rake.tooltip.png": s48,
  "data/review/spells/druid/ravage.icon.png": s49,
  "data/review/spells/druid/rebirth.icon.png": s50,
  "data/review/spells/druid/regrowth.icon.png": s51,
  "data/review/spells/druid/regrowth.tooltip.png": s52,
  "data/review/spells/druid/rejuvenation.icon.png": s53,
  "data/review/spells/druid/rejuvenation.tooltip.png": s54,
  "data/review/spells/druid/remove-curse.icon.png": s55,
  "data/review/spells/druid/remove-curse.tooltip.png": s56,
  "data/review/spells/druid/revive.icon.png": s57,
  "data/review/spells/druid/revive.r3.tooltip.png": s58,
  "data/review/spells/druid/rip.icon.png": s59,
  "data/review/spells/druid/shred.icon.png": s60,
  "data/review/spells/druid/skysight.icon.png": s61,
  "data/review/spells/druid/soothe-animal.icon.png": s62,
  "data/review/spells/druid/soothe-animal.tooltip.png": s63,
  "data/review/spells/druid/starfire.icon.png": s64,
  "data/review/spells/druid/starfire.tooltip.png": s65,
  "data/review/spells/druid/swipe.icon.png": s66,
  "data/review/spells/druid/thorns.icon.png": s67,
  "data/review/spells/druid/thorns.tooltip.png": s68,
  "data/review/spells/druid/tranquility.icon.png": s69,
  "data/review/spells/druid/tranquility.r1.tooltip.png": s70,
  "data/review/spells/druid/walk-on-air.icon.png": s71,
  "data/review/spells/druid/walk-on-air.tooltip.png": s72,
  "data/review/spells/druid/wind-blessed.icon.png": s73,
  "data/review/spells/druid/wrath.icon.png": s74,
  "data/review/spells/druid/wrath.r6.tooltip.png": s75,
}
