/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 51 crops the rogue spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/rogue/ambush.icon.png?url'
import s1 from '../../../../data/review/spells/rogue/armor-proficiency.icon.png?url'
import s2 from '../../../../data/review/spells/rogue/armor-proficiency.tooltip.png?url'
import s3 from '../../../../data/review/spells/rogue/attack.icon.png?url'
import s4 from '../../../../data/review/spells/rogue/backstab.icon.png?url'
import s5 from '../../../../data/review/spells/rogue/beast-slaying.icon.png?url'
import s6 from '../../../../data/review/spells/rogue/beast-slaying.tooltip.png?url'
import s7 from '../../../../data/review/spells/rogue/berserking.icon.png?url'
import s8 from '../../../../data/review/spells/rogue/blind.icon.png?url'
import s9 from '../../../../data/review/spells/rogue/cheap-shot.icon.png?url'
import s10 from '../../../../data/review/spells/rogue/detect-traps.icon.png?url'
import s11 from '../../../../data/review/spells/rogue/disarm-trap.icon.png?url'
import s12 from '../../../../data/review/spells/rogue/distract.icon.png?url'
import s13 from '../../../../data/review/spells/rogue/dodge.icon.png?url'
import s14 from '../../../../data/review/spells/rogue/dual-wield.icon.png?url'
import s15 from '../../../../data/review/spells/rogue/elunes-light.icon.png?url'
import s16 from '../../../../data/review/spells/rogue/evasion.icon.png?url'
import s17 from '../../../../data/review/spells/rogue/eviscerate.icon.png?url'
import s18 from '../../../../data/review/spells/rogue/expose-armor.icon.png?url'
import s19 from '../../../../data/review/spells/rogue/feint.icon.png?url'
import s20 from '../../../../data/review/spells/rogue/garrote.icon.png?url'
import s21 from '../../../../data/review/spells/rogue/gouge.icon.png?url'
import s22 from '../../../../data/review/spells/rogue/kick.icon.png?url'
import s23 from '../../../../data/review/spells/rogue/kidney-shot.icon.png?url'
import s24 from '../../../../data/review/spells/rogue/languages.icon.png?url'
import s25 from '../../../../data/review/spells/rogue/languages.tooltip.png?url'
import s26 from '../../../../data/review/spells/rogue/parry.icon.png?url'
import s27 from '../../../../data/review/spells/rogue/parry.tooltip.png?url'
import s28 from '../../../../data/review/spells/rogue/pick-lock.icon.png?url'
import s29 from '../../../../data/review/spells/rogue/pick-pocket.icon.png?url'
import s30 from '../../../../data/review/spells/rogue/quickness.icon.png?url'
import s31 from '../../../../data/review/spells/rogue/quickness.tooltip.png?url'
import s32 from '../../../../data/review/spells/rogue/rapid-regeneration.icon.png?url'
import s33 from '../../../../data/review/spells/rogue/rapid-regeneration.tooltip.png?url'
import s34 from '../../../../data/review/spells/rogue/regeneration.icon.png?url'
import s35 from '../../../../data/review/spells/rogue/regeneration.tooltip.png?url'
import s36 from '../../../../data/review/spells/rogue/rupture.icon.png?url'
import s37 from '../../../../data/review/spells/rogue/sap.icon.png?url'
import s38 from '../../../../data/review/spells/rogue/shadowmeld.icon.png?url'
import s39 from '../../../../data/review/spells/rogue/shadowmeld.tooltip.png?url'
import s40 from '../../../../data/review/spells/rogue/shoot-bow.icon.png?url'
import s41 from '../../../../data/review/spells/rogue/shoot-crossbow.icon.png?url'
import s42 from '../../../../data/review/spells/rogue/shoot-gun.icon.png?url'
import s43 from '../../../../data/review/spells/rogue/sinister-strike.icon.png?url'
import s44 from '../../../../data/review/spells/rogue/slice-and-dice.icon.png?url'
import s45 from '../../../../data/review/spells/rogue/sprint.icon.png?url'
import s46 from '../../../../data/review/spells/rogue/stealth.icon.png?url'
import s47 from '../../../../data/review/spells/rogue/throw.icon.png?url'
import s48 from '../../../../data/review/spells/rogue/throw.tooltip.png?url'
import s49 from '../../../../data/review/spells/rogue/vanish.icon.png?url'
import s50 from '../../../../data/review/spells/rogue/wisp-spirit.icon.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/rogue/ambush.icon.png": s0,
  "data/review/spells/rogue/armor-proficiency.icon.png": s1,
  "data/review/spells/rogue/armor-proficiency.tooltip.png": s2,
  "data/review/spells/rogue/attack.icon.png": s3,
  "data/review/spells/rogue/backstab.icon.png": s4,
  "data/review/spells/rogue/beast-slaying.icon.png": s5,
  "data/review/spells/rogue/beast-slaying.tooltip.png": s6,
  "data/review/spells/rogue/berserking.icon.png": s7,
  "data/review/spells/rogue/blind.icon.png": s8,
  "data/review/spells/rogue/cheap-shot.icon.png": s9,
  "data/review/spells/rogue/detect-traps.icon.png": s10,
  "data/review/spells/rogue/disarm-trap.icon.png": s11,
  "data/review/spells/rogue/distract.icon.png": s12,
  "data/review/spells/rogue/dodge.icon.png": s13,
  "data/review/spells/rogue/dual-wield.icon.png": s14,
  "data/review/spells/rogue/elunes-light.icon.png": s15,
  "data/review/spells/rogue/evasion.icon.png": s16,
  "data/review/spells/rogue/eviscerate.icon.png": s17,
  "data/review/spells/rogue/expose-armor.icon.png": s18,
  "data/review/spells/rogue/feint.icon.png": s19,
  "data/review/spells/rogue/garrote.icon.png": s20,
  "data/review/spells/rogue/gouge.icon.png": s21,
  "data/review/spells/rogue/kick.icon.png": s22,
  "data/review/spells/rogue/kidney-shot.icon.png": s23,
  "data/review/spells/rogue/languages.icon.png": s24,
  "data/review/spells/rogue/languages.tooltip.png": s25,
  "data/review/spells/rogue/parry.icon.png": s26,
  "data/review/spells/rogue/parry.tooltip.png": s27,
  "data/review/spells/rogue/pick-lock.icon.png": s28,
  "data/review/spells/rogue/pick-pocket.icon.png": s29,
  "data/review/spells/rogue/quickness.icon.png": s30,
  "data/review/spells/rogue/quickness.tooltip.png": s31,
  "data/review/spells/rogue/rapid-regeneration.icon.png": s32,
  "data/review/spells/rogue/rapid-regeneration.tooltip.png": s33,
  "data/review/spells/rogue/regeneration.icon.png": s34,
  "data/review/spells/rogue/regeneration.tooltip.png": s35,
  "data/review/spells/rogue/rupture.icon.png": s36,
  "data/review/spells/rogue/sap.icon.png": s37,
  "data/review/spells/rogue/shadowmeld.icon.png": s38,
  "data/review/spells/rogue/shadowmeld.tooltip.png": s39,
  "data/review/spells/rogue/shoot-bow.icon.png": s40,
  "data/review/spells/rogue/shoot-crossbow.icon.png": s41,
  "data/review/spells/rogue/shoot-gun.icon.png": s42,
  "data/review/spells/rogue/sinister-strike.icon.png": s43,
  "data/review/spells/rogue/slice-and-dice.icon.png": s44,
  "data/review/spells/rogue/sprint.icon.png": s45,
  "data/review/spells/rogue/stealth.icon.png": s46,
  "data/review/spells/rogue/throw.icon.png": s47,
  "data/review/spells/rogue/throw.tooltip.png": s48,
  "data/review/spells/rogue/vanish.icon.png": s49,
  "data/review/spells/rogue/wisp-spirit.icon.png": s50,
}
