/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 67 crops the warlock spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/warlock/armor-proficiency.icon.png?url'
import s1 from '../../../../data/review/spells/warlock/attack.icon.png?url'
import s2 from '../../../../data/review/spells/warlock/axe-specialization.icon.png?url'
import s3 from '../../../../data/review/spells/warlock/bane-of-agony.icon.png?url'
import s4 from '../../../../data/review/spells/warlock/banish.icon.png?url'
import s5 from '../../../../data/review/spells/warlock/blood-fury.icon.png?url'
import s6 from '../../../../data/review/spells/warlock/corruption.icon.png?url'
import s7 from '../../../../data/review/spells/warlock/corruption.tooltip.png?url'
import s8 from '../../../../data/review/spells/warlock/create-firestone.icon.png?url'
import s9 from '../../../../data/review/spells/warlock/create-healthstone.icon.png?url'
import s10 from '../../../../data/review/spells/warlock/create-soulstone.icon.png?url'
import s11 from '../../../../data/review/spells/warlock/create-soulstone.r2.tooltip.png?url'
import s12 from '../../../../data/review/spells/warlock/create-spellstone.icon.png?url'
import s13 from '../../../../data/review/spells/warlock/create-spellstone.tooltip.png?url'
import s14 from '../../../../data/review/spells/warlock/curse-of-recklessness.icon.png?url'
import s15 from '../../../../data/review/spells/warlock/curse-of-recklessness.tooltip.png?url'
import s16 from '../../../../data/review/spells/warlock/curse-of-the-elements.icon.png?url'
import s17 from '../../../../data/review/spells/warlock/curse-of-the-elements.tooltip.png?url'
import s18 from '../../../../data/review/spells/warlock/curse-of-tongues.icon.png?url'
import s19 from '../../../../data/review/spells/warlock/curse-of-weakness.icon.png?url'
import s20 from '../../../../data/review/spells/warlock/curse-of-weakness.tooltip.png?url'
import s21 from '../../../../data/review/spells/warlock/demon-armor.icon.png?url'
import s22 from '../../../../data/review/spells/warlock/demon-armor.r2.tooltip.png?url'
import s23 from '../../../../data/review/spells/warlock/demon-skin.icon.png?url'
import s24 from '../../../../data/review/spells/warlock/demon-skin.tooltip.png?url'
import s25 from '../../../../data/review/spells/warlock/detect-invisibility.icon.png?url'
import s26 from '../../../../data/review/spells/warlock/detect-invisibility.r2.tooltip.png?url'
import s27 from '../../../../data/review/spells/warlock/dodge.icon.png?url'
import s28 from '../../../../data/review/spells/warlock/drain-life.icon.png?url'
import s29 from '../../../../data/review/spells/warlock/drain-life.tooltip.png?url'
import s30 from '../../../../data/review/spells/warlock/drain-mana.icon.png?url'
import s31 from '../../../../data/review/spells/warlock/drain-mana.tooltip.png?url'
import s32 from '../../../../data/review/spells/warlock/drain-soul.icon.png?url'
import s33 from '../../../../data/review/spells/warlock/engineering-specialization.icon.png?url'
import s34 from '../../../../data/review/spells/warlock/escape-artist.icon.png?url'
import s35 from '../../../../data/review/spells/warlock/eureka.icon.png?url'
import s36 from '../../../../data/review/spells/warlock/expansive-mind.icon.png?url'
import s37 from '../../../../data/review/spells/warlock/eye-of-kilrogg.icon.png?url'
import s38 from '../../../../data/review/spells/warlock/eye-of-kilrogg.tooltip.png?url'
import s39 from '../../../../data/review/spells/warlock/fear.icon.png?url'
import s40 from '../../../../data/review/spells/warlock/fear.r2.tooltip.png?url'
import s41 from '../../../../data/review/spells/warlock/hardiness.icon.png?url'
import s42 from '../../../../data/review/spells/warlock/health-funnel.icon.png?url'
import s43 from '../../../../data/review/spells/warlock/immolate.icon.png?url'
import s44 from '../../../../data/review/spells/warlock/languages.icon.png?url'
import s45 from '../../../../data/review/spells/warlock/life-tap.icon.png?url'
import s46 from '../../../../data/review/spells/warlock/life-tap.r4.tooltip.png?url'
import s47 from '../../../../data/review/spells/warlock/rain-of-fire.icon.png?url'
import s48 from '../../../../data/review/spells/warlock/ritual-of-summoning.icon.png?url'
import s49 from '../../../../data/review/spells/warlock/ritual-of-summoning.tooltip.png?url'
import s50 from '../../../../data/review/spells/warlock/searing-pain.icon.png?url'
import s51 from '../../../../data/review/spells/warlock/sense-demons.icon.png?url'
import s52 from '../../../../data/review/spells/warlock/shadow-bolt.icon.png?url'
import s53 from '../../../../data/review/spells/warlock/shadow-bolt.tooltip.png?url'
import s54 from '../../../../data/review/spells/warlock/shadow-ward.icon.png?url'
import s55 from '../../../../data/review/spells/warlock/shadow-ward.tooltip.png?url'
import s56 from '../../../../data/review/spells/warlock/shatter-curse.icon.png?url'
import s57 from '../../../../data/review/spells/warlock/shoot.icon.png?url'
import s58 from '../../../../data/review/spells/warlock/subjugate-demon.icon.png?url'
import s59 from '../../../../data/review/spells/warlock/summon-felhunter.icon.png?url'
import s60 from '../../../../data/review/spells/warlock/summon-imp.icon.png?url'
import s61 from '../../../../data/review/spells/warlock/summon-incubus.icon.png?url'
import s62 from '../../../../data/review/spells/warlock/summon-incubus.tooltip.png?url'
import s63 from '../../../../data/review/spells/warlock/summon-succubus.icon.png?url'
import s64 from '../../../../data/review/spells/warlock/summon-succubus.tooltip.png?url'
import s65 from '../../../../data/review/spells/warlock/summon-voidwalker.icon.png?url'
import s66 from '../../../../data/review/spells/warlock/unending-breath.icon.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/warlock/armor-proficiency.icon.png": s0,
  "data/review/spells/warlock/attack.icon.png": s1,
  "data/review/spells/warlock/axe-specialization.icon.png": s2,
  "data/review/spells/warlock/bane-of-agony.icon.png": s3,
  "data/review/spells/warlock/banish.icon.png": s4,
  "data/review/spells/warlock/blood-fury.icon.png": s5,
  "data/review/spells/warlock/corruption.icon.png": s6,
  "data/review/spells/warlock/corruption.tooltip.png": s7,
  "data/review/spells/warlock/create-firestone.icon.png": s8,
  "data/review/spells/warlock/create-healthstone.icon.png": s9,
  "data/review/spells/warlock/create-soulstone.icon.png": s10,
  "data/review/spells/warlock/create-soulstone.r2.tooltip.png": s11,
  "data/review/spells/warlock/create-spellstone.icon.png": s12,
  "data/review/spells/warlock/create-spellstone.tooltip.png": s13,
  "data/review/spells/warlock/curse-of-recklessness.icon.png": s14,
  "data/review/spells/warlock/curse-of-recklessness.tooltip.png": s15,
  "data/review/spells/warlock/curse-of-the-elements.icon.png": s16,
  "data/review/spells/warlock/curse-of-the-elements.tooltip.png": s17,
  "data/review/spells/warlock/curse-of-tongues.icon.png": s18,
  "data/review/spells/warlock/curse-of-weakness.icon.png": s19,
  "data/review/spells/warlock/curse-of-weakness.tooltip.png": s20,
  "data/review/spells/warlock/demon-armor.icon.png": s21,
  "data/review/spells/warlock/demon-armor.r2.tooltip.png": s22,
  "data/review/spells/warlock/demon-skin.icon.png": s23,
  "data/review/spells/warlock/demon-skin.tooltip.png": s24,
  "data/review/spells/warlock/detect-invisibility.icon.png": s25,
  "data/review/spells/warlock/detect-invisibility.r2.tooltip.png": s26,
  "data/review/spells/warlock/dodge.icon.png": s27,
  "data/review/spells/warlock/drain-life.icon.png": s28,
  "data/review/spells/warlock/drain-life.tooltip.png": s29,
  "data/review/spells/warlock/drain-mana.icon.png": s30,
  "data/review/spells/warlock/drain-mana.tooltip.png": s31,
  "data/review/spells/warlock/drain-soul.icon.png": s32,
  "data/review/spells/warlock/engineering-specialization.icon.png": s33,
  "data/review/spells/warlock/escape-artist.icon.png": s34,
  "data/review/spells/warlock/eureka.icon.png": s35,
  "data/review/spells/warlock/expansive-mind.icon.png": s36,
  "data/review/spells/warlock/eye-of-kilrogg.icon.png": s37,
  "data/review/spells/warlock/eye-of-kilrogg.tooltip.png": s38,
  "data/review/spells/warlock/fear.icon.png": s39,
  "data/review/spells/warlock/fear.r2.tooltip.png": s40,
  "data/review/spells/warlock/hardiness.icon.png": s41,
  "data/review/spells/warlock/health-funnel.icon.png": s42,
  "data/review/spells/warlock/immolate.icon.png": s43,
  "data/review/spells/warlock/languages.icon.png": s44,
  "data/review/spells/warlock/life-tap.icon.png": s45,
  "data/review/spells/warlock/life-tap.r4.tooltip.png": s46,
  "data/review/spells/warlock/rain-of-fire.icon.png": s47,
  "data/review/spells/warlock/ritual-of-summoning.icon.png": s48,
  "data/review/spells/warlock/ritual-of-summoning.tooltip.png": s49,
  "data/review/spells/warlock/searing-pain.icon.png": s50,
  "data/review/spells/warlock/sense-demons.icon.png": s51,
  "data/review/spells/warlock/shadow-bolt.icon.png": s52,
  "data/review/spells/warlock/shadow-bolt.tooltip.png": s53,
  "data/review/spells/warlock/shadow-ward.icon.png": s54,
  "data/review/spells/warlock/shadow-ward.tooltip.png": s55,
  "data/review/spells/warlock/shatter-curse.icon.png": s56,
  "data/review/spells/warlock/shoot.icon.png": s57,
  "data/review/spells/warlock/subjugate-demon.icon.png": s58,
  "data/review/spells/warlock/summon-felhunter.icon.png": s59,
  "data/review/spells/warlock/summon-imp.icon.png": s60,
  "data/review/spells/warlock/summon-incubus.icon.png": s61,
  "data/review/spells/warlock/summon-incubus.tooltip.png": s62,
  "data/review/spells/warlock/summon-succubus.icon.png": s63,
  "data/review/spells/warlock/summon-succubus.tooltip.png": s64,
  "data/review/spells/warlock/summon-voidwalker.icon.png": s65,
  "data/review/spells/warlock/unending-breath.icon.png": s66,
}
