/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 73 crops the mage spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/mage/amplify-magic.icon.png?url'
import s1 from '../../../../data/review/spells/mage/arcane-blast.icon.png?url'
import s2 from '../../../../data/review/spells/mage/arcane-explosion.icon.png?url'
import s3 from '../../../../data/review/spells/mage/arcane-explosion.tooltip.png?url'
import s4 from '../../../../data/review/spells/mage/arcane-intellect.icon.png?url'
import s5 from '../../../../data/review/spells/mage/arcane-intellect.tooltip.png?url'
import s6 from '../../../../data/review/spells/mage/arcane-missiles.icon.png?url'
import s7 from '../../../../data/review/spells/mage/arcane-missiles.tooltip.png?url'
import s8 from '../../../../data/review/spells/mage/armor-proficiency.icon.png?url'
import s9 from '../../../../data/review/spells/mage/armor-proficiency.tooltip.png?url'
import s10 from '../../../../data/review/spells/mage/attack.icon.png?url'
import s11 from '../../../../data/review/spells/mage/blink.icon.png?url'
import s12 from '../../../../data/review/spells/mage/blink.tooltip.png?url'
import s13 from '../../../../data/review/spells/mage/blizzard.icon.png?url'
import s14 from '../../../../data/review/spells/mage/comprehend-scroll.icon.png?url'
import s15 from '../../../../data/review/spells/mage/comprehend-scroll.tooltip.png?url'
import s16 from '../../../../data/review/spells/mage/cone-of-cold.icon.png?url'
import s17 from '../../../../data/review/spells/mage/cone-of-cold.tooltip.png?url'
import s18 from '../../../../data/review/spells/mage/conjure-food.icon.png?url'
import s19 from '../../../../data/review/spells/mage/conjure-food.tooltip.png?url'
import s20 from '../../../../data/review/spells/mage/conjure-mana-agate.icon.png?url'
import s21 from '../../../../data/review/spells/mage/conjure-mana-agate.tooltip.png?url'
import s22 from '../../../../data/review/spells/mage/conjure-mana-jade.icon.png?url'
import s23 from '../../../../data/review/spells/mage/conjure-water.icon.png?url'
import s24 from '../../../../data/review/spells/mage/conjure-water.tooltip.png?url'
import s25 from '../../../../data/review/spells/mage/counterspell.icon.png?url'
import s26 from '../../../../data/review/spells/mage/counterspell.tooltip.png?url'
import s27 from '../../../../data/review/spells/mage/dampen-magic.icon.png?url'
import s28 from '../../../../data/review/spells/mage/dampen-magic.tooltip.png?url'
import s29 from '../../../../data/review/spells/mage/dodge.icon.png?url'
import s30 from '../../../../data/review/spells/mage/engineering-specialization.icon.png?url'
import s31 from '../../../../data/review/spells/mage/engineering-specialization.tooltip.png?url'
import s32 from '../../../../data/review/spells/mage/escape-artist.icon.png?url'
import s33 from '../../../../data/review/spells/mage/eureka.icon.png?url'
import s34 from '../../../../data/review/spells/mage/eureka.tooltip.png?url'
import s35 from '../../../../data/review/spells/mage/evocation.icon.png?url'
import s36 from '../../../../data/review/spells/mage/evocation.tooltip.png?url'
import s37 from '../../../../data/review/spells/mage/expansive-mind.icon.png?url'
import s38 from '../../../../data/review/spells/mage/expansive-mind.tooltip.png?url'
import s39 from '../../../../data/review/spells/mage/fire-blast.icon.png?url'
import s40 from '../../../../data/review/spells/mage/fire-ward.icon.png?url'
import s41 from '../../../../data/review/spells/mage/fireball.icon.png?url'
import s42 from '../../../../data/review/spells/mage/fireball.r7.tooltip.png?url'
import s43 from '../../../../data/review/spells/mage/flamestrike.icon.png?url'
import s44 from '../../../../data/review/spells/mage/flamestrike.r3.tooltip.png?url'
import s45 from '../../../../data/review/spells/mage/frost-armor.icon.png?url'
import s46 from '../../../../data/review/spells/mage/frost-armor.tooltip.png?url'
import s47 from '../../../../data/review/spells/mage/frost-nova.icon.png?url'
import s48 from '../../../../data/review/spells/mage/frost-ward.icon.png?url'
import s49 from '../../../../data/review/spells/mage/frost-ward.r2.tooltip.png?url'
import s50 from '../../../../data/review/spells/mage/frostbolt.icon.png?url'
import s51 from '../../../../data/review/spells/mage/frostbolt.tooltip.png?url'
import s52 from '../../../../data/review/spells/mage/ice-armor.icon.png?url'
import s53 from '../../../../data/review/spells/mage/languages.icon.png?url'
import s54 from '../../../../data/review/spells/mage/languages.tooltip.png?url'
import s55 from '../../../../data/review/spells/mage/mage-armor.icon.png?url'
import s56 from '../../../../data/review/spells/mage/mage-armor.tooltip.png?url'
import s57 from '../../../../data/review/spells/mage/mana-shield.icon.png?url'
import s58 from '../../../../data/review/spells/mage/mana-shield.tooltip.png?url'
import s59 from '../../../../data/review/spells/mage/polymorph.icon.png?url'
import s60 from '../../../../data/review/spells/mage/presence-of-mind.icon.png?url'
import s61 from '../../../../data/review/spells/mage/remove-lesser-curse.icon.png?url'
import s62 from '../../../../data/review/spells/mage/scorch.icon.png?url'
import s63 from '../../../../data/review/spells/mage/scorch.r3.tooltip.png?url'
import s64 from '../../../../data/review/spells/mage/shoot.icon.png?url'
import s65 from '../../../../data/review/spells/mage/slow-fall.icon.png?url'
import s66 from '../../../../data/review/spells/mage/slow-fall.tooltip.png?url'
import s67 from '../../../../data/review/spells/mage/teleport-darnassus.icon.png?url'
import s68 from '../../../../data/review/spells/mage/teleport-darnassus.tooltip.png?url'
import s69 from '../../../../data/review/spells/mage/teleport-ironforge.icon.png?url'
import s70 from '../../../../data/review/spells/mage/teleport-ironforge.tooltip.png?url'
import s71 from '../../../../data/review/spells/mage/teleport-stormwind.icon.png?url'
import s72 from '../../../../data/review/spells/mage/teleport-stormwind.tooltip.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/mage/amplify-magic.icon.png": s0,
  "data/review/spells/mage/arcane-blast.icon.png": s1,
  "data/review/spells/mage/arcane-explosion.icon.png": s2,
  "data/review/spells/mage/arcane-explosion.tooltip.png": s3,
  "data/review/spells/mage/arcane-intellect.icon.png": s4,
  "data/review/spells/mage/arcane-intellect.tooltip.png": s5,
  "data/review/spells/mage/arcane-missiles.icon.png": s6,
  "data/review/spells/mage/arcane-missiles.tooltip.png": s7,
  "data/review/spells/mage/armor-proficiency.icon.png": s8,
  "data/review/spells/mage/armor-proficiency.tooltip.png": s9,
  "data/review/spells/mage/attack.icon.png": s10,
  "data/review/spells/mage/blink.icon.png": s11,
  "data/review/spells/mage/blink.tooltip.png": s12,
  "data/review/spells/mage/blizzard.icon.png": s13,
  "data/review/spells/mage/comprehend-scroll.icon.png": s14,
  "data/review/spells/mage/comprehend-scroll.tooltip.png": s15,
  "data/review/spells/mage/cone-of-cold.icon.png": s16,
  "data/review/spells/mage/cone-of-cold.tooltip.png": s17,
  "data/review/spells/mage/conjure-food.icon.png": s18,
  "data/review/spells/mage/conjure-food.tooltip.png": s19,
  "data/review/spells/mage/conjure-mana-agate.icon.png": s20,
  "data/review/spells/mage/conjure-mana-agate.tooltip.png": s21,
  "data/review/spells/mage/conjure-mana-jade.icon.png": s22,
  "data/review/spells/mage/conjure-water.icon.png": s23,
  "data/review/spells/mage/conjure-water.tooltip.png": s24,
  "data/review/spells/mage/counterspell.icon.png": s25,
  "data/review/spells/mage/counterspell.tooltip.png": s26,
  "data/review/spells/mage/dampen-magic.icon.png": s27,
  "data/review/spells/mage/dampen-magic.tooltip.png": s28,
  "data/review/spells/mage/dodge.icon.png": s29,
  "data/review/spells/mage/engineering-specialization.icon.png": s30,
  "data/review/spells/mage/engineering-specialization.tooltip.png": s31,
  "data/review/spells/mage/escape-artist.icon.png": s32,
  "data/review/spells/mage/eureka.icon.png": s33,
  "data/review/spells/mage/eureka.tooltip.png": s34,
  "data/review/spells/mage/evocation.icon.png": s35,
  "data/review/spells/mage/evocation.tooltip.png": s36,
  "data/review/spells/mage/expansive-mind.icon.png": s37,
  "data/review/spells/mage/expansive-mind.tooltip.png": s38,
  "data/review/spells/mage/fire-blast.icon.png": s39,
  "data/review/spells/mage/fire-ward.icon.png": s40,
  "data/review/spells/mage/fireball.icon.png": s41,
  "data/review/spells/mage/fireball.r7.tooltip.png": s42,
  "data/review/spells/mage/flamestrike.icon.png": s43,
  "data/review/spells/mage/flamestrike.r3.tooltip.png": s44,
  "data/review/spells/mage/frost-armor.icon.png": s45,
  "data/review/spells/mage/frost-armor.tooltip.png": s46,
  "data/review/spells/mage/frost-nova.icon.png": s47,
  "data/review/spells/mage/frost-ward.icon.png": s48,
  "data/review/spells/mage/frost-ward.r2.tooltip.png": s49,
  "data/review/spells/mage/frostbolt.icon.png": s50,
  "data/review/spells/mage/frostbolt.tooltip.png": s51,
  "data/review/spells/mage/ice-armor.icon.png": s52,
  "data/review/spells/mage/languages.icon.png": s53,
  "data/review/spells/mage/languages.tooltip.png": s54,
  "data/review/spells/mage/mage-armor.icon.png": s55,
  "data/review/spells/mage/mage-armor.tooltip.png": s56,
  "data/review/spells/mage/mana-shield.icon.png": s57,
  "data/review/spells/mage/mana-shield.tooltip.png": s58,
  "data/review/spells/mage/polymorph.icon.png": s59,
  "data/review/spells/mage/presence-of-mind.icon.png": s60,
  "data/review/spells/mage/remove-lesser-curse.icon.png": s61,
  "data/review/spells/mage/scorch.icon.png": s62,
  "data/review/spells/mage/scorch.r3.tooltip.png": s63,
  "data/review/spells/mage/shoot.icon.png": s64,
  "data/review/spells/mage/slow-fall.icon.png": s65,
  "data/review/spells/mage/slow-fall.tooltip.png": s66,
  "data/review/spells/mage/teleport-darnassus.icon.png": s67,
  "data/review/spells/mage/teleport-darnassus.tooltip.png": s68,
  "data/review/spells/mage/teleport-ironforge.icon.png": s69,
  "data/review/spells/mage/teleport-ironforge.tooltip.png": s70,
  "data/review/spells/mage/teleport-stormwind.icon.png": s71,
  "data/review/spells/mage/teleport-stormwind.tooltip.png": s72,
}
