/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 99 crops the hunter spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/hunter/aimed-shot.icon.png?url'
import s1 from '../../../../data/review/spells/hunter/arcane-shot.icon.png?url'
import s2 from '../../../../data/review/spells/hunter/arcane-shot.tooltip.png?url'
import s3 from '../../../../data/review/spells/hunter/armor-proficiency.icon.png?url'
import s4 from '../../../../data/review/spells/hunter/aspect-of-the-beast.icon.png?url'
import s5 from '../../../../data/review/spells/hunter/aspect-of-the-cheetah.icon.png?url'
import s6 from '../../../../data/review/spells/hunter/aspect-of-the-hawk.icon.png?url'
import s7 from '../../../../data/review/spells/hunter/aspect-of-the-hawk.r4.tooltip.png?url'
import s8 from '../../../../data/review/spells/hunter/aspect-of-the-monkey.icon.png?url'
import s9 from '../../../../data/review/spells/hunter/aspect-of-the-monkey.tooltip.png?url'
import s10 from '../../../../data/review/spells/hunter/assist.icon.png?url'
import s11 from '../../../../data/review/spells/hunter/attack.icon.png?url'
import s12 from '../../../../data/review/spells/hunter/auto-shot.icon.png?url'
import s13 from '../../../../data/review/spells/hunter/auto-shot.tooltip.png?url'
import s14 from '../../../../data/review/spells/hunter/beast-lore.icon.png?url'
import s15 from '../../../../data/review/spells/hunter/beast-lore.tooltip.png?url'
import s16 from '../../../../data/review/spells/hunter/beast-training.icon.png?url'
import s17 from '../../../../data/review/spells/hunter/call-owl.icon.png?url'
import s18 from '../../../../data/review/spells/hunter/call-owl.tooltip.png?url'
import s19 from '../../../../data/review/spells/hunter/claw.icon.png?url'
import s20 from '../../../../data/review/spells/hunter/concussive-shot.icon.png?url'
import s21 from '../../../../data/review/spells/hunter/concussive-shot.tooltip.png?url'
import s22 from '../../../../data/review/spells/hunter/defensive.icon.png?url'
import s23 from '../../../../data/review/spells/hunter/disengage.icon.png?url'
import s24 from '../../../../data/review/spells/hunter/dismiss-pet.icon.png?url'
import s25 from '../../../../data/review/spells/hunter/dismiss-pet.tooltip.png?url'
import s26 from '../../../../data/review/spells/hunter/distracting-shot.icon.png?url'
import s27 from '../../../../data/review/spells/hunter/dive.icon.png?url'
import s28 from '../../../../data/review/spells/hunter/dodge.icon.png?url'
import s29 from '../../../../data/review/spells/hunter/dual-wield.icon.png?url'
import s30 from '../../../../data/review/spells/hunter/eagle-eye.icon.png?url'
import s31 from '../../../../data/review/spells/hunter/eagle-eye.tooltip.png?url'
import s32 from '../../../../data/review/spells/hunter/explosive-trap.icon.png?url'
import s33 from '../../../../data/review/spells/hunter/eyes-of-the-beast.icon.png?url'
import s34 from '../../../../data/review/spells/hunter/eyes-of-the-beast.tooltip.png?url'
import s35 from '../../../../data/review/spells/hunter/feed-pet.icon.png?url'
import s36 from '../../../../data/review/spells/hunter/feed-pet.tooltip.png?url'
import s37 from '../../../../data/review/spells/hunter/feign-death.icon.png?url'
import s38 from '../../../../data/review/spells/hunter/feign-death.tooltip.png?url'
import s39 from '../../../../data/review/spells/hunter/flare.icon.png?url'
import s40 from '../../../../data/review/spells/hunter/flare.tooltip.png?url'
import s41 from '../../../../data/review/spells/hunter/follow.icon.png?url'
import s42 from '../../../../data/review/spells/hunter/freezing-trap.icon.png?url'
import s43 from '../../../../data/review/spells/hunter/freezing-trap.tooltip.png?url'
import s44 from '../../../../data/review/spells/hunter/frost-trap.icon.png?url'
import s45 from '../../../../data/review/spells/hunter/frost-trap.tooltip.png?url'
import s46 from '../../../../data/review/spells/hunter/great-stamina.icon.png?url'
import s47 from '../../../../data/review/spells/hunter/great-stamina.r6.tooltip.png?url'
import s48 from '../../../../data/review/spells/hunter/hunters-mark.icon.png?url'
import s49 from '../../../../data/review/spells/hunter/hunters-mark.r2.tooltip.png?url'
import s50 from '../../../../data/review/spells/hunter/immolation-trap.icon.png?url'
import s51 from '../../../../data/review/spells/hunter/languages.icon.png?url'
import s52 from '../../../../data/review/spells/hunter/mend-pet.icon.png?url'
import s53 from '../../../../data/review/spells/hunter/mend-pet.tooltip.png?url'
import s54 from '../../../../data/review/spells/hunter/mine.icon.png?url'
import s55 from '../../../../data/review/spells/hunter/mine.r3.tooltip.png?url'
import s56 from '../../../../data/review/spells/hunter/mongoose-bite.icon.png?url'
import s57 from '../../../../data/review/spells/hunter/mongoose-bite.tooltip.png?url'
import s58 from '../../../../data/review/spells/hunter/move-to.icon.png?url'
import s59 from '../../../../data/review/spells/hunter/move-to.tooltip.png?url'
import s60 from '../../../../data/review/spells/hunter/multi-shot.icon.png?url'
import s61 from '../../../../data/review/spells/hunter/natural-armor.icon.png?url'
import s62 from '../../../../data/review/spells/hunter/parry.icon.png?url'
import s63 from '../../../../data/review/spells/hunter/perception.icon.png?url'
import s64 from '../../../../data/review/spells/hunter/rapid-fire.icon.png?url'
import s65 from '../../../../data/review/spells/hunter/rapid-fire.tooltip.png?url'
import s66 from '../../../../data/review/spells/hunter/raptor-strike.icon.png?url'
import s67 from '../../../../data/review/spells/hunter/raptor-strike.tooltip.png?url'
import s68 from '../../../../data/review/spells/hunter/revive-pet.icon.png?url'
import s69 from '../../../../data/review/spells/hunter/revive-pet.tooltip.png?url'
import s70 from '../../../../data/review/spells/hunter/scare-beast.icon.png?url'
import s71 from '../../../../data/review/spells/hunter/scare-beast.r2.tooltip.png?url'
import s72 from '../../../../data/review/spells/hunter/scorpid-sting.icon.png?url'
import s73 from '../../../../data/review/spells/hunter/scorpid-sting.r1.tooltip.png?url'
import s74 from '../../../../data/review/spells/hunter/serpent-sting.icon.png?url'
import s75 from '../../../../data/review/spells/hunter/serpent-sting.r5.tooltip.png?url'
import s76 from '../../../../data/review/spells/hunter/stay.icon.png?url'
import s77 from '../../../../data/review/spells/hunter/stay.tooltip.png?url'
import s78 from '../../../../data/review/spells/hunter/sword-specialization.icon.png?url'
import s79 from '../../../../data/review/spells/hunter/tame-beast.icon.png?url'
import s80 from '../../../../data/review/spells/hunter/tame-beast.tooltip.png?url'
import s81 from '../../../../data/review/spells/hunter/the-human-spirit.icon.png?url'
import s82 from '../../../../data/review/spells/hunter/throw.icon.png?url'
import s83 from '../../../../data/review/spells/hunter/track-beasts.icon.png?url'
import s84 from '../../../../data/review/spells/hunter/track-beasts.tooltip.png?url'
import s85 from '../../../../data/review/spells/hunter/track-demons.icon.png?url'
import s86 from '../../../../data/review/spells/hunter/track-demons.tooltip.png?url'
import s87 from '../../../../data/review/spells/hunter/track-elementals.icon.png?url'
import s88 from '../../../../data/review/spells/hunter/track-elementals.tooltip.png?url'
import s89 from '../../../../data/review/spells/hunter/track-hidden.icon.png?url'
import s90 from '../../../../data/review/spells/hunter/track-hidden.tooltip.png?url'
import s91 from '../../../../data/review/spells/hunter/track-humanoids.icon.png?url'
import s92 from '../../../../data/review/spells/hunter/track-humanoids.tooltip.png?url'
import s93 from '../../../../data/review/spells/hunter/track-undead.icon.png?url'
import s94 from '../../../../data/review/spells/hunter/viper-sting.icon.png?url'
import s95 from '../../../../data/review/spells/hunter/viper-sting.r1.tooltip.png?url'
import s96 from '../../../../data/review/spells/hunter/will-to-survive.icon.png?url'
import s97 from '../../../../data/review/spells/hunter/wing-clip.icon.png?url'
import s98 from '../../../../data/review/spells/hunter/wing-clip.r2.tooltip.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/hunter/aimed-shot.icon.png": s0,
  "data/review/spells/hunter/arcane-shot.icon.png": s1,
  "data/review/spells/hunter/arcane-shot.tooltip.png": s2,
  "data/review/spells/hunter/armor-proficiency.icon.png": s3,
  "data/review/spells/hunter/aspect-of-the-beast.icon.png": s4,
  "data/review/spells/hunter/aspect-of-the-cheetah.icon.png": s5,
  "data/review/spells/hunter/aspect-of-the-hawk.icon.png": s6,
  "data/review/spells/hunter/aspect-of-the-hawk.r4.tooltip.png": s7,
  "data/review/spells/hunter/aspect-of-the-monkey.icon.png": s8,
  "data/review/spells/hunter/aspect-of-the-monkey.tooltip.png": s9,
  "data/review/spells/hunter/assist.icon.png": s10,
  "data/review/spells/hunter/attack.icon.png": s11,
  "data/review/spells/hunter/auto-shot.icon.png": s12,
  "data/review/spells/hunter/auto-shot.tooltip.png": s13,
  "data/review/spells/hunter/beast-lore.icon.png": s14,
  "data/review/spells/hunter/beast-lore.tooltip.png": s15,
  "data/review/spells/hunter/beast-training.icon.png": s16,
  "data/review/spells/hunter/call-owl.icon.png": s17,
  "data/review/spells/hunter/call-owl.tooltip.png": s18,
  "data/review/spells/hunter/claw.icon.png": s19,
  "data/review/spells/hunter/concussive-shot.icon.png": s20,
  "data/review/spells/hunter/concussive-shot.tooltip.png": s21,
  "data/review/spells/hunter/defensive.icon.png": s22,
  "data/review/spells/hunter/disengage.icon.png": s23,
  "data/review/spells/hunter/dismiss-pet.icon.png": s24,
  "data/review/spells/hunter/dismiss-pet.tooltip.png": s25,
  "data/review/spells/hunter/distracting-shot.icon.png": s26,
  "data/review/spells/hunter/dive.icon.png": s27,
  "data/review/spells/hunter/dodge.icon.png": s28,
  "data/review/spells/hunter/dual-wield.icon.png": s29,
  "data/review/spells/hunter/eagle-eye.icon.png": s30,
  "data/review/spells/hunter/eagle-eye.tooltip.png": s31,
  "data/review/spells/hunter/explosive-trap.icon.png": s32,
  "data/review/spells/hunter/eyes-of-the-beast.icon.png": s33,
  "data/review/spells/hunter/eyes-of-the-beast.tooltip.png": s34,
  "data/review/spells/hunter/feed-pet.icon.png": s35,
  "data/review/spells/hunter/feed-pet.tooltip.png": s36,
  "data/review/spells/hunter/feign-death.icon.png": s37,
  "data/review/spells/hunter/feign-death.tooltip.png": s38,
  "data/review/spells/hunter/flare.icon.png": s39,
  "data/review/spells/hunter/flare.tooltip.png": s40,
  "data/review/spells/hunter/follow.icon.png": s41,
  "data/review/spells/hunter/freezing-trap.icon.png": s42,
  "data/review/spells/hunter/freezing-trap.tooltip.png": s43,
  "data/review/spells/hunter/frost-trap.icon.png": s44,
  "data/review/spells/hunter/frost-trap.tooltip.png": s45,
  "data/review/spells/hunter/great-stamina.icon.png": s46,
  "data/review/spells/hunter/great-stamina.r6.tooltip.png": s47,
  "data/review/spells/hunter/hunters-mark.icon.png": s48,
  "data/review/spells/hunter/hunters-mark.r2.tooltip.png": s49,
  "data/review/spells/hunter/immolation-trap.icon.png": s50,
  "data/review/spells/hunter/languages.icon.png": s51,
  "data/review/spells/hunter/mend-pet.icon.png": s52,
  "data/review/spells/hunter/mend-pet.tooltip.png": s53,
  "data/review/spells/hunter/mine.icon.png": s54,
  "data/review/spells/hunter/mine.r3.tooltip.png": s55,
  "data/review/spells/hunter/mongoose-bite.icon.png": s56,
  "data/review/spells/hunter/mongoose-bite.tooltip.png": s57,
  "data/review/spells/hunter/move-to.icon.png": s58,
  "data/review/spells/hunter/move-to.tooltip.png": s59,
  "data/review/spells/hunter/multi-shot.icon.png": s60,
  "data/review/spells/hunter/natural-armor.icon.png": s61,
  "data/review/spells/hunter/parry.icon.png": s62,
  "data/review/spells/hunter/perception.icon.png": s63,
  "data/review/spells/hunter/rapid-fire.icon.png": s64,
  "data/review/spells/hunter/rapid-fire.tooltip.png": s65,
  "data/review/spells/hunter/raptor-strike.icon.png": s66,
  "data/review/spells/hunter/raptor-strike.tooltip.png": s67,
  "data/review/spells/hunter/revive-pet.icon.png": s68,
  "data/review/spells/hunter/revive-pet.tooltip.png": s69,
  "data/review/spells/hunter/scare-beast.icon.png": s70,
  "data/review/spells/hunter/scare-beast.r2.tooltip.png": s71,
  "data/review/spells/hunter/scorpid-sting.icon.png": s72,
  "data/review/spells/hunter/scorpid-sting.r1.tooltip.png": s73,
  "data/review/spells/hunter/serpent-sting.icon.png": s74,
  "data/review/spells/hunter/serpent-sting.r5.tooltip.png": s75,
  "data/review/spells/hunter/stay.icon.png": s76,
  "data/review/spells/hunter/stay.tooltip.png": s77,
  "data/review/spells/hunter/sword-specialization.icon.png": s78,
  "data/review/spells/hunter/tame-beast.icon.png": s79,
  "data/review/spells/hunter/tame-beast.tooltip.png": s80,
  "data/review/spells/hunter/the-human-spirit.icon.png": s81,
  "data/review/spells/hunter/throw.icon.png": s82,
  "data/review/spells/hunter/track-beasts.icon.png": s83,
  "data/review/spells/hunter/track-beasts.tooltip.png": s84,
  "data/review/spells/hunter/track-demons.icon.png": s85,
  "data/review/spells/hunter/track-demons.tooltip.png": s86,
  "data/review/spells/hunter/track-elementals.icon.png": s87,
  "data/review/spells/hunter/track-elementals.tooltip.png": s88,
  "data/review/spells/hunter/track-hidden.icon.png": s89,
  "data/review/spells/hunter/track-hidden.tooltip.png": s90,
  "data/review/spells/hunter/track-humanoids.icon.png": s91,
  "data/review/spells/hunter/track-humanoids.tooltip.png": s92,
  "data/review/spells/hunter/track-undead.icon.png": s93,
  "data/review/spells/hunter/viper-sting.icon.png": s94,
  "data/review/spells/hunter/viper-sting.r1.tooltip.png": s95,
  "data/review/spells/hunter/will-to-survive.icon.png": s96,
  "data/review/spells/hunter/wing-clip.icon.png": s97,
  "data/review/spells/hunter/wing-clip.r2.tooltip.png": s98,
}
