/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 16 crops the rogue spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/rogue/armor-proficiency.icon.png?url'
import s1 from '../../../../data/review/spells/rogue/attack.icon.png?url'
import s2 from '../../../../data/review/spells/rogue/dodge.icon.png?url'
import s3 from '../../../../data/review/spells/rogue/dual-wield.icon.png?url'
import s4 from '../../../../data/review/spells/rogue/elunes-light.icon.png?url'
import s5 from '../../../../data/review/spells/rogue/languages.icon.png?url'
import s6 from '../../../../data/review/spells/rogue/parry.icon.png?url'
import s7 from '../../../../data/review/spells/rogue/pick-lock.icon.png?url'
import s8 from '../../../../data/review/spells/rogue/quickness.icon.png?url'
import s9 from '../../../../data/review/spells/rogue/shadowmeld.icon.png?url'
import s10 from '../../../../data/review/spells/rogue/shadowmeld.tooltip.png?url'
import s11 from '../../../../data/review/spells/rogue/shoot-bow.icon.png?url'
import s12 from '../../../../data/review/spells/rogue/shoot-crossbow.icon.png?url'
import s13 from '../../../../data/review/spells/rogue/shoot-gun.icon.png?url'
import s14 from '../../../../data/review/spells/rogue/throw.icon.png?url'
import s15 from '../../../../data/review/spells/rogue/wisp-spirit.icon.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/rogue/armor-proficiency.icon.png": s0,
  "data/review/spells/rogue/attack.icon.png": s1,
  "data/review/spells/rogue/dodge.icon.png": s2,
  "data/review/spells/rogue/dual-wield.icon.png": s3,
  "data/review/spells/rogue/elunes-light.icon.png": s4,
  "data/review/spells/rogue/languages.icon.png": s5,
  "data/review/spells/rogue/parry.icon.png": s6,
  "data/review/spells/rogue/pick-lock.icon.png": s7,
  "data/review/spells/rogue/quickness.icon.png": s8,
  "data/review/spells/rogue/shadowmeld.icon.png": s9,
  "data/review/spells/rogue/shadowmeld.tooltip.png": s10,
  "data/review/spells/rogue/shoot-bow.icon.png": s11,
  "data/review/spells/rogue/shoot-crossbow.icon.png": s12,
  "data/review/spells/rogue/shoot-gun.icon.png": s13,
  "data/review/spells/rogue/throw.icon.png": s14,
  "data/review/spells/rogue/wisp-spirit.icon.png": s15,
}
