/**
 * GENERATED by scripts/gen-data-index.mjs - do not edit.
 *
 * The 68 crops the shaman spell page renders or links: the row icon of
 * every entry and the frame behind every full tooltip. One module per class,
 * reached through the lazy glob in spellCrop.ts, so a visitor downloads the
 * URLs of one class and never the whole spellbook.
 */
import s0 from '../../../../data/review/spells/shaman/ancestral-spirit.icon.png?url'
import s1 from '../../../../data/review/spells/shaman/armor-proficiency.icon.png?url'
import s2 from '../../../../data/review/spells/shaman/astral-recall.icon.png?url'
import s3 from '../../../../data/review/spells/shaman/attack.icon.png?url'
import s4 from '../../../../data/review/spells/shaman/axe-specialization.icon.png?url'
import s5 from '../../../../data/review/spells/shaman/block.icon.png?url'
import s6 from '../../../../data/review/spells/shaman/blood-fury.icon.png?url'
import s7 from '../../../../data/review/spells/shaman/call-of-the-ancestors.icon.png?url'
import s8 from '../../../../data/review/spells/shaman/call-of-the-elements.icon.png?url'
import s9 from '../../../../data/review/spells/shaman/chain-lightning.icon.png?url'
import s10 from '../../../../data/review/spells/shaman/cultivation.icon.png?url'
import s11 from '../../../../data/review/spells/shaman/cure-disease.icon.png?url'
import s12 from '../../../../data/review/spells/shaman/cure-poison.icon.png?url'
import s13 from '../../../../data/review/spells/shaman/disease-cleansing-totem.icon.png?url'
import s14 from '../../../../data/review/spells/shaman/dodge.icon.png?url'
import s15 from '../../../../data/review/spells/shaman/earth-shock.icon.png?url'
import s16 from '../../../../data/review/spells/shaman/earthbind-totem.icon.png?url'
import s17 from '../../../../data/review/spells/shaman/endurance.icon.png?url'
import s18 from '../../../../data/review/spells/shaman/far-sight.icon.png?url'
import s19 from '../../../../data/review/spells/shaman/fire-nova.icon.png?url'
import s20 from '../../../../data/review/spells/shaman/fire-resistance-totem.icon.png?url'
import s21 from '../../../../data/review/spells/shaman/flame-shock.icon.png?url'
import s22 from '../../../../data/review/spells/shaman/flame-shock.r3.tooltip.png?url'
import s23 from '../../../../data/review/spells/shaman/flame-shock.tooltip.png?url'
import s24 from '../../../../data/review/spells/shaman/flametongue-totem.icon.png?url'
import s25 from '../../../../data/review/spells/shaman/flametongue-weapon.icon.png?url'
import s26 from '../../../../data/review/spells/shaman/frost-resistance-totem.icon.png?url'
import s27 from '../../../../data/review/spells/shaman/frost-shock.icon.png?url'
import s28 from '../../../../data/review/spells/shaman/frostbrand-weapon.icon.png?url'
import s29 from '../../../../data/review/spells/shaman/ghost-wolf.icon.png?url'
import s30 from '../../../../data/review/spells/shaman/grounding-totem.icon.png?url'
import s31 from '../../../../data/review/spells/shaman/hardiness.icon.png?url'
import s32 from '../../../../data/review/spells/shaman/healing-stream-totem.icon.png?url'
import s33 from '../../../../data/review/spells/shaman/healing-wave.icon.png?url'
import s34 from '../../../../data/review/spells/shaman/languages.icon.png?url'
import s35 from '../../../../data/review/spells/shaman/lesser-healing-wave.icon.png?url'
import s36 from '../../../../data/review/spells/shaman/lightning-bolt.icon.png?url'
import s37 from '../../../../data/review/spells/shaman/lightning-shield.icon.png?url'
import s38 from '../../../../data/review/spells/shaman/magma-totem.icon.png?url'
import s39 from '../../../../data/review/spells/shaman/mana-spring-totem.icon.png?url'
import s40 from '../../../../data/review/spells/shaman/nature-resistance-totem.icon.png?url'
import s41 from '../../../../data/review/spells/shaman/nature-resistance-totem.r1.tooltip.png?url'
import s42 from '../../../../data/review/spells/shaman/plainsrunning.icon.png?url'
import s43 from '../../../../data/review/spells/shaman/plainsrunning.tooltip.png?url'
import s44 from '../../../../data/review/spells/shaman/poison-cleansing-totem.icon.png?url'
import s45 from '../../../../data/review/spells/shaman/purge.icon.png?url'
import s46 from '../../../../data/review/spells/shaman/reincarnation-passive.icon.png?url'
import s47 from '../../../../data/review/spells/shaman/rockbiter-weapon.icon.png?url'
import s48 from '../../../../data/review/spells/shaman/searing-totem.icon.png?url'
import s49 from '../../../../data/review/spells/shaman/sentry-totem.icon.png?url'
import s50 from '../../../../data/review/spells/shaman/shatter-curse.icon.png?url'
import s51 from '../../../../data/review/spells/shaman/stoneclaw-totem.icon.png?url'
import s52 from '../../../../data/review/spells/shaman/stoneclaw-totem.tooltip.png?url'
import s53 from '../../../../data/review/spells/shaman/stoneskin-totem.icon.png?url'
import s54 from '../../../../data/review/spells/shaman/stoneskin-totem.tooltip.png?url'
import s55 from '../../../../data/review/spells/shaman/strength-of-earth-totem.icon.png?url'
import s56 from '../../../../data/review/spells/shaman/totemic-projection.icon.png?url'
import s57 from '../../../../data/review/spells/shaman/totemic-projection.tooltip.png?url'
import s58 from '../../../../data/review/spells/shaman/totemic-recall.icon.png?url'
import s59 from '../../../../data/review/spells/shaman/tremor-totem.icon.png?url'
import s60 from '../../../../data/review/spells/shaman/war-stomp.icon.png?url'
import s61 from '../../../../data/review/spells/shaman/water-breathing.icon.png?url'
import s62 from '../../../../data/review/spells/shaman/water-walking.icon.png?url'
import s63 from '../../../../data/review/spells/shaman/windfury-totem.icon.png?url'
import s64 from '../../../../data/review/spells/shaman/windfury-totem.tooltip.png?url'
import s65 from '../../../../data/review/spells/shaman/windfury-weapon.icon.png?url'
import s66 from '../../../../data/review/spells/shaman/windwall-totem.icon.png?url'
import s67 from '../../../../data/review/spells/shaman/windwall-totem.tooltip.png?url'

export const spellCropUrls: Record<string, string> = {
  "data/review/spells/shaman/ancestral-spirit.icon.png": s0,
  "data/review/spells/shaman/armor-proficiency.icon.png": s1,
  "data/review/spells/shaman/astral-recall.icon.png": s2,
  "data/review/spells/shaman/attack.icon.png": s3,
  "data/review/spells/shaman/axe-specialization.icon.png": s4,
  "data/review/spells/shaman/block.icon.png": s5,
  "data/review/spells/shaman/blood-fury.icon.png": s6,
  "data/review/spells/shaman/call-of-the-ancestors.icon.png": s7,
  "data/review/spells/shaman/call-of-the-elements.icon.png": s8,
  "data/review/spells/shaman/chain-lightning.icon.png": s9,
  "data/review/spells/shaman/cultivation.icon.png": s10,
  "data/review/spells/shaman/cure-disease.icon.png": s11,
  "data/review/spells/shaman/cure-poison.icon.png": s12,
  "data/review/spells/shaman/disease-cleansing-totem.icon.png": s13,
  "data/review/spells/shaman/dodge.icon.png": s14,
  "data/review/spells/shaman/earth-shock.icon.png": s15,
  "data/review/spells/shaman/earthbind-totem.icon.png": s16,
  "data/review/spells/shaman/endurance.icon.png": s17,
  "data/review/spells/shaman/far-sight.icon.png": s18,
  "data/review/spells/shaman/fire-nova.icon.png": s19,
  "data/review/spells/shaman/fire-resistance-totem.icon.png": s20,
  "data/review/spells/shaman/flame-shock.icon.png": s21,
  "data/review/spells/shaman/flame-shock.r3.tooltip.png": s22,
  "data/review/spells/shaman/flame-shock.tooltip.png": s23,
  "data/review/spells/shaman/flametongue-totem.icon.png": s24,
  "data/review/spells/shaman/flametongue-weapon.icon.png": s25,
  "data/review/spells/shaman/frost-resistance-totem.icon.png": s26,
  "data/review/spells/shaman/frost-shock.icon.png": s27,
  "data/review/spells/shaman/frostbrand-weapon.icon.png": s28,
  "data/review/spells/shaman/ghost-wolf.icon.png": s29,
  "data/review/spells/shaman/grounding-totem.icon.png": s30,
  "data/review/spells/shaman/hardiness.icon.png": s31,
  "data/review/spells/shaman/healing-stream-totem.icon.png": s32,
  "data/review/spells/shaman/healing-wave.icon.png": s33,
  "data/review/spells/shaman/languages.icon.png": s34,
  "data/review/spells/shaman/lesser-healing-wave.icon.png": s35,
  "data/review/spells/shaman/lightning-bolt.icon.png": s36,
  "data/review/spells/shaman/lightning-shield.icon.png": s37,
  "data/review/spells/shaman/magma-totem.icon.png": s38,
  "data/review/spells/shaman/mana-spring-totem.icon.png": s39,
  "data/review/spells/shaman/nature-resistance-totem.icon.png": s40,
  "data/review/spells/shaman/nature-resistance-totem.r1.tooltip.png": s41,
  "data/review/spells/shaman/plainsrunning.icon.png": s42,
  "data/review/spells/shaman/plainsrunning.tooltip.png": s43,
  "data/review/spells/shaman/poison-cleansing-totem.icon.png": s44,
  "data/review/spells/shaman/purge.icon.png": s45,
  "data/review/spells/shaman/reincarnation-passive.icon.png": s46,
  "data/review/spells/shaman/rockbiter-weapon.icon.png": s47,
  "data/review/spells/shaman/searing-totem.icon.png": s48,
  "data/review/spells/shaman/sentry-totem.icon.png": s49,
  "data/review/spells/shaman/shatter-curse.icon.png": s50,
  "data/review/spells/shaman/stoneclaw-totem.icon.png": s51,
  "data/review/spells/shaman/stoneclaw-totem.tooltip.png": s52,
  "data/review/spells/shaman/stoneskin-totem.icon.png": s53,
  "data/review/spells/shaman/stoneskin-totem.tooltip.png": s54,
  "data/review/spells/shaman/strength-of-earth-totem.icon.png": s55,
  "data/review/spells/shaman/totemic-projection.icon.png": s56,
  "data/review/spells/shaman/totemic-projection.tooltip.png": s57,
  "data/review/spells/shaman/totemic-recall.icon.png": s58,
  "data/review/spells/shaman/tremor-totem.icon.png": s59,
  "data/review/spells/shaman/war-stomp.icon.png": s60,
  "data/review/spells/shaman/water-breathing.icon.png": s61,
  "data/review/spells/shaman/water-walking.icon.png": s62,
  "data/review/spells/shaman/windfury-totem.icon.png": s63,
  "data/review/spells/shaman/windfury-totem.tooltip.png": s64,
  "data/review/spells/shaman/windfury-weapon.icon.png": s65,
  "data/review/spells/shaman/windwall-totem.icon.png": s66,
  "data/review/spells/shaman/windwall-totem.tooltip.png": s67,
}
